ALTER TABLE "events" DROP CONSTRAINT "events_event_type_check";--> statement-breakpoint
ALTER TABLE "job_queue" DROP CONSTRAINT "job_queue_status_check";--> statement-breakpoint
ALTER TABLE "notification_routes" DROP CONSTRAINT "notification_routes_event_name_check";--> statement-breakpoint
ALTER TABLE "job_queue" ADD COLUMN "leased_until" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "job_queue" ADD COLUMN "heartbeat_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "job_queue" ADD COLUMN "max_attempts" integer DEFAULT 5 NOT NULL;--> statement-breakpoint
CREATE INDEX "job_queue_lease" ON "job_queue" USING btree ("leased_until") WHERE "job_queue"."status" = 'running';--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_event_type_check" CHECK ("events"."event_type" IN ('allocator.allocated','allocator.failed','allocator.requested','auditor.completed','auditor.failed','auditor.rejected','auditor.started','auditor.verdict','checker.completed','checker.failed','checker.rejected','checker.started','checker.verdict','ci.failed','ci.passed','ci.started','cost.failed','cost.resolved','cost.unattributable','credential.failed','credential.loaded','credential.requested','gate.failed','gate.passed','gate.started','github.branch.pushed','github.failed','github.pr.created','github.pr.merged','github.pr.ready','hello.completed','hello.ssh_completed','hello.ssh_started','hello.started','job.dead_lettered','merge.blocked','merge.completed','merge.conflict','merge.failed','merge.queued','notification.enqueued','notification.failed','notification.sent','phase1.fixture.ci_pending','phase1.fixture.completed','phase1.fixture.failed','phase1.fixture.started','planner.completed','planner.failed','planner.rerequested','planner.started','planner.subtasks.emitted','recovery.inspection_opened','recovery.replan_queued','recovery.revise_routed','recovery.rollback_queued','redaction.raw_access','review.approved','review.changes_requested','review.requested','run.completed','run.failed','run.queued','run.started','runner.allocated','runner.failed','runner.released','task.completed','task.failed','task.queued','task.started','usage.accounting.observed','usage.window.observed','usage.window.pressure','workspace.failed','workspace.git_captured','workspace.prepared','writer.completed','writer.failed','writer.started','writer.subtask.completed','writer.subtask.failed','writer.subtask.started'));--> statement-breakpoint
ALTER TABLE "job_queue" ADD CONSTRAINT "job_queue_status_check" CHECK ("job_queue"."status" IN ('queued','claimed','running','done','failed','cancelled','dead_letter'));--> statement-breakpoint
ALTER TABLE "notification_routes" ADD CONSTRAINT "notification_routes_event_name_check" CHECK ("notification_routes"."event_name" IN ('allocator.allocated','allocator.failed','allocator.requested','auditor.completed','auditor.failed','auditor.rejected','auditor.started','auditor.verdict','checker.completed','checker.failed','checker.rejected','checker.started','checker.verdict','ci.failed','ci.passed','ci.started','cost.failed','cost.resolved','cost.unattributable','credential.failed','credential.loaded','credential.requested','gate.failed','gate.passed','gate.started','github.branch.pushed','github.failed','github.pr.created','github.pr.merged','github.pr.ready','hello.completed','hello.ssh_completed','hello.ssh_started','hello.started','job.dead_lettered','merge.blocked','merge.completed','merge.conflict','merge.failed','merge.queued','notification.enqueued','notification.failed','notification.sent','phase1.fixture.ci_pending','phase1.fixture.completed','phase1.fixture.failed','phase1.fixture.started','planner.completed','planner.failed','planner.rerequested','planner.started','planner.subtasks.emitted','recovery.inspection_opened','recovery.replan_queued','recovery.revise_routed','recovery.rollback_queued','redaction.raw_access','review.approved','review.changes_requested','review.requested','run.completed','run.failed','run.queued','run.started','runner.allocated','runner.failed','runner.released','task.completed','task.failed','task.queued','task.started','usage.accounting.observed','usage.window.observed','usage.window.pressure','workspace.failed','workspace.git_captured','workspace.prepared','writer.completed','writer.failed','writer.started','writer.subtask.completed','writer.subtask.failed','writer.subtask.started'));
