CREATE TABLE "org_quotas" (
	"org_id" text NOT NULL,
	"window_key" text DEFAULT 'default' NOT NULL,
	"run_limit" bigint,
	"token_limit" bigint,
	"credit_limit" numeric(20, 6),
	"runs_used" bigint DEFAULT 0 NOT NULL,
	"tokens_used" bigint DEFAULT 0 NOT NULL,
	"credits_used" numeric(20, 6) DEFAULT 0 NOT NULL,
	"reset_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "events" DROP CONSTRAINT "events_event_type_check";--> statement-breakpoint
ALTER TABLE "notification_routes" DROP CONSTRAINT "notification_routes_event_name_check";--> statement-breakpoint
ALTER TABLE "runs" DROP CONSTRAINT "runs_outcome_check";--> statement-breakpoint
ALTER TABLE "org_quotas" ADD CONSTRAINT "org_quotas_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "org_quotas_org_window_unique" ON "org_quotas" USING btree ("org_id","window_key");--> statement-breakpoint
CREATE INDEX "org_quotas_org_id" ON "org_quotas" USING btree ("org_id");--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_event_type_check" CHECK ("events"."event_type" IN ('allocator.allocated','allocator.failed','allocator.requested','auditor.completed','auditor.failed','auditor.rejected','auditor.started','auditor.verdict','checker.completed','checker.failed','checker.rejected','checker.started','checker.verdict','ci.failed','ci.passed','ci.started','cost.failed','cost.resolved','cost.unattributable','credential.failed','credential.loaded','credential.requested','gate.failed','gate.passed','gate.started','github.branch.pushed','github.failed','github.pr.created','github.pr.merged','github.pr.ready','hello.completed','hello.ssh_completed','hello.ssh_started','hello.started','job.dead_lettered','merge.blocked','merge.completed','merge.conflict','merge.failed','merge.queued','notification.enqueued','notification.failed','notification.sent','phase1.fixture.ci_pending','phase1.fixture.completed','phase1.fixture.failed','phase1.fixture.started','planner.completed','planner.failed','planner.rerequested','planner.started','planner.subtasks.emitted','recovery.inspection_opened','recovery.replan_queued','recovery.revise_routed','recovery.rollback_queued','redaction.raw_access','review.approved','review.changes_requested','review.requested','run.completed','run.failed','run.queued','run.quota_exceeded','run.started','runner.allocated','runner.failed','runner.released','task.completed','task.failed','task.queued','task.started','usage.accounting.observed','usage.window.observed','usage.window.pressure','workspace.failed','workspace.git_captured','workspace.prepared','writer.completed','writer.failed','writer.started','writer.subtask.completed','writer.subtask.failed','writer.subtask.started'));--> statement-breakpoint
ALTER TABLE "notification_routes" ADD CONSTRAINT "notification_routes_event_name_check" CHECK ("notification_routes"."event_name" IN ('allocator.allocated','allocator.failed','allocator.requested','auditor.completed','auditor.failed','auditor.rejected','auditor.started','auditor.verdict','checker.completed','checker.failed','checker.rejected','checker.started','checker.verdict','ci.failed','ci.passed','ci.started','cost.failed','cost.resolved','cost.unattributable','credential.failed','credential.loaded','credential.requested','gate.failed','gate.passed','gate.started','github.branch.pushed','github.failed','github.pr.created','github.pr.merged','github.pr.ready','hello.completed','hello.ssh_completed','hello.ssh_started','hello.started','job.dead_lettered','merge.blocked','merge.completed','merge.conflict','merge.failed','merge.queued','notification.enqueued','notification.failed','notification.sent','phase1.fixture.ci_pending','phase1.fixture.completed','phase1.fixture.failed','phase1.fixture.started','planner.completed','planner.failed','planner.rerequested','planner.started','planner.subtasks.emitted','recovery.inspection_opened','recovery.replan_queued','recovery.revise_routed','recovery.rollback_queued','redaction.raw_access','review.approved','review.changes_requested','review.requested','run.completed','run.failed','run.queued','run.quota_exceeded','run.started','runner.allocated','runner.failed','runner.released','task.completed','task.failed','task.queued','task.started','usage.accounting.observed','usage.window.observed','usage.window.pressure','workspace.failed','workspace.git_captured','workspace.prepared','writer.completed','writer.failed','writer.started','writer.subtask.completed','writer.subtask.failed','writer.subtask.started'));--> statement-breakpoint
ALTER TABLE "runs" ADD CONSTRAINT "runs_outcome_check" CHECK ("runs"."outcome" IS NULL OR "runs"."outcome" IN ('hello_complete','phase1_fixture_complete','phase2_easy_complete','phase2_medium_complete','halted','escape_hatch_hit','retry_budget_exhausted','window_exhausted','quota_exceeded','cancelled','hello_world_complete','ok','failed','pending'));
