-- Mission-complete WAVE-1 event-vocabulary FREEZE seed. Adds the 52 new names
-- the wave's consumer nodes emit to the platform-global `event_types` catalog:
--   * the integration lifecycle vocabulary (in-3) — integration.requirement.*,
--     .reconcile.*, .resource.*, .binding.*, .grant.*, .runtime.attached,
--     .validation.*, .stimulus.emitted, .effect.observed, .recovery.enqueued,
--     .teardown.* (frozen from the integrations spec §3); and
--   * the runtime behavior-proof vocabulary (rv-25) — behavior.*, design.render.*,
--     gate.behavior_proof.bound, integration.proof.recorded,
--     merge.batch.behavior_failed/culprit_set_identified, post_merge.behavior.*,
--     deployment.promoted/rolled_back (frozen from the runtime spec §7).
--
-- Seeded BEFORE any consumer emits, so the events.event_type FK domain covers
-- every frozen name. Mirrors db/src/eventTypesSeed.ts (regenerated from the Zod
-- EventRegistry + eventDefaultSeverity via `codegen:events`). ON CONFLICT DO
-- NOTHING keeps re-application idempotent, matching migration 0042.
INSERT INTO "event_types" ("name", "default_severity") VALUES
  ('behavior.action.observed', 'info'),
  ('behavior.assertion.observed', 'info'),
  ('behavior.attempt.started', 'info'),
  ('behavior.contract.compilation_started', 'info'),
  ('behavior.contract.compiled', 'info'),
  ('behavior.contract.rejected', 'warn'),
  ('behavior.effect.observed', 'info'),
  ('behavior.fragment.authoring_started', 'info'),
  ('behavior.fragment.missing', 'info'),
  ('behavior.fragment.validated', 'info'),
  ('behavior.respec.requested', 'warn'),
  ('behavior.shard.started', 'info'),
  ('behavior.verdict.recorded', 'info'),
  ('behavior.verification.completed', 'info'),
  ('behavior.verification.started', 'info'),
  ('deployment.promoted', 'info'),
  ('deployment.rolled_back', 'warn'),
  ('design.render.captured', 'info'),
  ('design.render.verdict_recorded', 'info'),
  ('gate.behavior_proof.bound', 'info'),
  ('integration.binding.committed', 'info'),
  ('integration.binding.drifted', 'warn'),
  ('integration.binding.materialized', 'info'),
  ('integration.effect.observed', 'info'),
  ('integration.grant.linked', 'info'),
  ('integration.grant.requested', 'warn'),
  ('integration.grant.revoked', 'warn'),
  ('integration.grant.rotated', 'info'),
  ('integration.grant.validated', 'info'),
  ('integration.proof.recorded', 'info'),
  ('integration.reconcile.fixed_point', 'warn'),
  ('integration.reconcile.retry_scheduled', 'info'),
  ('integration.reconcile.started', 'info'),
  ('integration.reconcile.state_unknown', 'warn'),
  ('integration.recovery.enqueued', 'info'),
  ('integration.requirement.derived', 'info'),
  ('integration.requirement.superseded', 'info'),
  ('integration.resource.adopted', 'info'),
  ('integration.resource.discovered', 'info'),
  ('integration.resource.provisioned', 'info'),
  ('integration.resource.selected', 'info'),
  ('integration.runtime.attached', 'info'),
  ('integration.stimulus.emitted', 'info'),
  ('integration.teardown.completed', 'info'),
  ('integration.teardown.failed', 'warn'),
  ('integration.validation.failed', 'warn'),
  ('integration.validation.passed', 'info'),
  ('integration.validation.started', 'info'),
  ('merge.batch.behavior_failed', 'warn'),
  ('merge.batch.culprit_set_identified', 'warn'),
  ('post_merge.behavior.failed', 'warn'),
  ('post_merge.behavior.verified', 'info')
ON CONFLICT ("name") DO NOTHING;
