CREATE TABLE "quarantined_tests" (
	"id" text PRIMARY KEY NOT NULL,
	"project_id" text NOT NULL,
	"check_name" text NOT NULL,
	"toggled_sha_count" integer NOT NULL,
	"observation_count" integer NOT NULL,
	"evidence" jsonb NOT NULL,
	"quarantined_at" timestamp with time zone DEFAULT now() NOT NULL,
	"cleared_at" timestamp with time zone,
	"cleared_by" text,
	CONSTRAINT "quarantined_tests_toggled_check" CHECK ("quarantined_tests"."toggled_sha_count" >= 1),
	CONSTRAINT "quarantined_tests_observation_check" CHECK ("quarantined_tests"."observation_count" >= 1)
);
--> statement-breakpoint
ALTER TABLE "events" DROP CONSTRAINT "events_event_type_check";--> statement-breakpoint
ALTER TABLE "notification_routes" DROP CONSTRAINT "notification_routes_event_name_check";--> statement-breakpoint
ALTER TABLE "workflow_insights" DROP CONSTRAINT "workflow_insights_kind_check";--> statement-breakpoint
ALTER TABLE "quarantined_tests" ADD CONSTRAINT "quarantined_tests_project_id_projects_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("project_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quarantined_tests" ADD CONSTRAINT "quarantined_tests_cleared_by_users_id_fk" FOREIGN KEY ("cleared_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "quarantined_tests_active_unique" ON "quarantined_tests" USING btree ("project_id","check_name") WHERE "quarantined_tests"."cleared_at" IS NULL;--> statement-breakpoint
CREATE INDEX "quarantined_tests_project" ON "quarantined_tests" USING btree ("project_id","quarantined_at" desc);--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_event_type_check" CHECK ("events"."event_type" IN ('allocator.allocated','allocator.failed','allocator.requested','auditor.completed','auditor.failed','auditor.rejected','auditor.started','auditor.verdict','benchmark.accept.failed','benchmark.accept.passed','checker.completed','checker.failed','checker.rejected','checker.started','checker.verdict','ci.failed','ci.flaky.detected','ci.passed','ci.started','ci.test.quarantined','cost.failed','cost.resolved','cost.unattributable','credential.failed','credential.loaded','credential.requested','dag.budget.paused','dag.drained','dag.spec.enqueued','dag.spec.percolated','dag.spec.percolating','dag.spec.percolation_deferred','dag.spec.percolation_replan','dag.spec.speculation_held','dag.spec.speculative','gate.failed','gate.passed','gate.started','github.branch.pushed','github.failed','github.pr.created','github.pr.merged','github.pr.ready','hello.completed','hello.ssh_completed','hello.ssh_started','hello.started','job.dead_lettered','merge.batch.bisecting','merge.batch.checking','merge.batch.culprit','merge.batch.passed','merge.behind','merge.blocked','merge.completed','merge.conflict','merge.conflict.irreconcilable','merge.conflict.replan_routed','merge.conflict.resolved','merge.conflict.resolving','merge.dequeued','merge.failed','merge.integration_cleaned','merge.queue.advanced','merge.queued','merge.rebased','merge.retargeted','merge.speculative_held','notification.enqueued','notification.failed','notification.sent','phase1.fixture.ci_pending','phase1.fixture.completed','phase1.fixture.failed','phase1.fixture.started','planner.completed','planner.failed','planner.rerequested','planner.started','planner.subtasks.emitted','recovery.inspection_opened','recovery.replan_queued','recovery.revise_routed','recovery.rollback_queued','redaction.raw_access','review.approved','review.auto_approved','review.changes_requested','review.requested','run.completed','run.failed','run.queued','run.started','runner.allocated','runner.failed','runner.released','task.completed','task.failed','task.queued','task.started','usage.accounting.observed','usage.window.observed','usage.window.pressure','workspace.failed','workspace.git_captured','workspace.prepared','writer.completed','writer.failed','writer.started','writer.subtask.completed','writer.subtask.failed','writer.subtask.started'));--> statement-breakpoint
ALTER TABLE "notification_routes" ADD CONSTRAINT "notification_routes_event_name_check" CHECK ("notification_routes"."event_name" IN ('allocator.allocated','allocator.failed','allocator.requested','auditor.completed','auditor.failed','auditor.rejected','auditor.started','auditor.verdict','benchmark.accept.failed','benchmark.accept.passed','checker.completed','checker.failed','checker.rejected','checker.started','checker.verdict','ci.failed','ci.flaky.detected','ci.passed','ci.started','ci.test.quarantined','cost.failed','cost.resolved','cost.unattributable','credential.failed','credential.loaded','credential.requested','dag.budget.paused','dag.drained','dag.spec.enqueued','dag.spec.percolated','dag.spec.percolating','dag.spec.percolation_deferred','dag.spec.percolation_replan','dag.spec.speculation_held','dag.spec.speculative','gate.failed','gate.passed','gate.started','github.branch.pushed','github.failed','github.pr.created','github.pr.merged','github.pr.ready','hello.completed','hello.ssh_completed','hello.ssh_started','hello.started','job.dead_lettered','merge.batch.bisecting','merge.batch.checking','merge.batch.culprit','merge.batch.passed','merge.behind','merge.blocked','merge.completed','merge.conflict','merge.conflict.irreconcilable','merge.conflict.replan_routed','merge.conflict.resolved','merge.conflict.resolving','merge.dequeued','merge.failed','merge.integration_cleaned','merge.queue.advanced','merge.queued','merge.rebased','merge.retargeted','merge.speculative_held','notification.enqueued','notification.failed','notification.sent','phase1.fixture.ci_pending','phase1.fixture.completed','phase1.fixture.failed','phase1.fixture.started','planner.completed','planner.failed','planner.rerequested','planner.started','planner.subtasks.emitted','recovery.inspection_opened','recovery.replan_queued','recovery.revise_routed','recovery.rollback_queued','redaction.raw_access','review.approved','review.auto_approved','review.changes_requested','review.requested','run.completed','run.failed','run.queued','run.started','runner.allocated','runner.failed','runner.released','task.completed','task.failed','task.queued','task.started','usage.accounting.observed','usage.window.observed','usage.window.pressure','workspace.failed','workspace.git_captured','workspace.prepared','writer.completed','writer.failed','writer.started','writer.subtask.completed','writer.subtask.failed','writer.subtask.started'));--> statement-breakpoint
ALTER TABLE "workflow_insights" ADD CONSTRAINT "workflow_insights_kind_check" CHECK ("workflow_insights"."kind" IN ('retry_hotspot','model_mismatch','pace_anomaly','stuck','review_stall','ci_flaky'));--> statement-breakpoint

-- P2e-1 RLS for the quarantine surface, mirroring migration 0030's
-- deny-by-default pattern for project-keyed tables (the same 3c-style EXISTS
-- subquery `workflow_insights` uses). `quarantined_tests` has no own org_id; it
-- is scoped through its parent project. The EXISTS subquery runs under the SAME
-- `app.current_org_id` GUC, so it resolves the project only when the project
-- belongs to the scoped org — a cross-org quarantine row is both unreadable AND
-- unwritable. Idempotent via DROP POLICY IF EXISTS so re-running never errors.
ALTER TABLE quarantined_tests ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS rls_org_isolation ON quarantined_tests;--> statement-breakpoint
CREATE POLICY rls_org_isolation ON quarantined_tests FOR ALL
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.project_id = quarantined_tests.project_id))
  WITH CHECK (EXISTS (SELECT 1 FROM projects p WHERE p.project_id = quarantined_tests.project_id));
