CREATE TABLE "ci_test_results" (
	"id" text PRIMARY KEY NOT NULL,
	"project_id" text NOT NULL,
	"org_id" text NOT NULL,
	"test_id" text NOT NULL,
	"file" text,
	"suite" text,
	"head_sha" text NOT NULL,
	"run_id" text NOT NULL,
	"attempt" integer DEFAULT 1 NOT NULL,
	"outcome" text NOT NULL,
	"duration_ms" integer,
	"retries" integer DEFAULT 0 NOT NULL,
	"observed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ci_test_results_outcome_check" CHECK ("ci_test_results"."outcome" IN ('passed','failed','error','skipped')),
	CONSTRAINT "ci_test_results_attempt_check" CHECK ("ci_test_results"."attempt" >= 1),
	CONSTRAINT "ci_test_results_retries_check" CHECK ("ci_test_results"."retries" >= 0)
);
--> statement-breakpoint
ALTER TABLE "events" DROP CONSTRAINT "events_event_type_check";--> statement-breakpoint
ALTER TABLE "notification_routes" DROP CONSTRAINT "notification_routes_event_name_check";--> statement-breakpoint
ALTER TABLE "ci_test_results" ADD CONSTRAINT "ci_test_results_project_id_projects_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("project_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ci_test_results" ADD CONSTRAINT "ci_test_results_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ci_test_results" ADD CONSTRAINT "ci_test_results_run_id_runs_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("run_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ci_test_results_org_id" ON "ci_test_results" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "ci_test_results_org_project" ON "ci_test_results" USING btree ("org_id","project_id");--> statement-breakpoint
CREATE INDEX "ci_test_results_project_test" ON "ci_test_results" USING btree ("project_id","test_id","observed_at" desc);--> statement-breakpoint
CREATE INDEX "ci_test_results_run" ON "ci_test_results" USING btree ("run_id");--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_event_type_check" CHECK ("events"."event_type" IN ('allocator.allocated','allocator.failed','allocator.requested','app_env.ci_propagated','app_env.runtime_attached','auditor.completed','auditor.failed','auditor.rejected','auditor.started','auditor.verdict','benchmark.accept.failed','benchmark.accept.passed','checker.completed','checker.failed','checker.rejected','checker.started','checker.verdict','ci.failed','ci.flaky.detected','ci.passed','ci.started','ci.test.quarantined','ci.tests.reported','cost.ceiling_unreachable','cost.failed','cost.resolved','cost.unattributable','cost.unattributed','credential.failed','credential.loaded','credential.requested','credential.scoped_token_minted','dag.budget.paused','dag.concurrency.saturated','dag.drained','dag.spec.enqueued','dag.spec.needs_attention','dag.spec.percolated','dag.spec.percolating','dag.spec.percolation_deferred','dag.spec.percolation_replan','dag.spec.speculation_held','dag.spec.speculative','dag.spec.unstranded','gate.advisory_failed','gate.failed','gate.passed','gate.started','github.branch.pushed','github.failed','github.pr.created','github.pr.merged','github.pr.ready','hello.completed','hello.ssh_completed','hello.ssh_started','hello.started','integration.provisioned','issue.opened','job.dead_lettered','merge.batch.bisecting','merge.batch.checking','merge.batch.culprit','merge.batch.infra_blocked','merge.batch.passed','merge.behind','merge.blocked','merge.completed','merge.conflict','merge.conflict.irreconcilable','merge.conflict.replan_routed','merge.conflict.resolved','merge.conflict.resolving','merge.dequeued','merge.failed','merge.integration_cleaned','merge.post_merge_failed','merge.queue.advanced','merge.queue.infra_blocked','merge.queued','merge.rebased','merge.retargeted','merge.speculative_held','notification.enqueued','notification.failed','notification.sent','phase1.fixture.ci_pending','phase1.fixture.completed','phase1.fixture.failed','phase1.fixture.started','planner.completed','planner.failed','planner.rerequested','planner.started','planner.subtasks.emitted','recovery.inspection_opened','recovery.replan_queued','recovery.revise_routed','recovery.rollback_queued','redaction.raw_access','review.approved','review.auto_approved','review.changes_requested','review.requested','run.completed','run.failed','run.queued','run.started','runner.allocated','runner.failed','runner.released','task.completed','task.failed','task.queued','task.started','usage.accounting.observed','usage.window.observed','usage.window.pressure','workspace.failed','workspace.git_captured','workspace.prepared','writer.completed','writer.failed','writer.started','writer.subtask.completed','writer.subtask.failed','writer.subtask.started'));--> statement-breakpoint
ALTER TABLE "notification_routes" ADD CONSTRAINT "notification_routes_event_name_check" CHECK ("notification_routes"."event_name" IN ('allocator.allocated','allocator.failed','allocator.requested','app_env.ci_propagated','app_env.runtime_attached','auditor.completed','auditor.failed','auditor.rejected','auditor.started','auditor.verdict','benchmark.accept.failed','benchmark.accept.passed','checker.completed','checker.failed','checker.rejected','checker.started','checker.verdict','ci.failed','ci.flaky.detected','ci.passed','ci.started','ci.test.quarantined','ci.tests.reported','cost.ceiling_unreachable','cost.failed','cost.resolved','cost.unattributable','cost.unattributed','credential.failed','credential.loaded','credential.requested','credential.scoped_token_minted','dag.budget.paused','dag.concurrency.saturated','dag.drained','dag.spec.enqueued','dag.spec.needs_attention','dag.spec.percolated','dag.spec.percolating','dag.spec.percolation_deferred','dag.spec.percolation_replan','dag.spec.speculation_held','dag.spec.speculative','dag.spec.unstranded','gate.advisory_failed','gate.failed','gate.passed','gate.started','github.branch.pushed','github.failed','github.pr.created','github.pr.merged','github.pr.ready','hello.completed','hello.ssh_completed','hello.ssh_started','hello.started','integration.provisioned','issue.opened','job.dead_lettered','merge.batch.bisecting','merge.batch.checking','merge.batch.culprit','merge.batch.infra_blocked','merge.batch.passed','merge.behind','merge.blocked','merge.completed','merge.conflict','merge.conflict.irreconcilable','merge.conflict.replan_routed','merge.conflict.resolved','merge.conflict.resolving','merge.dequeued','merge.failed','merge.integration_cleaned','merge.post_merge_failed','merge.queue.advanced','merge.queue.infra_blocked','merge.queued','merge.rebased','merge.retargeted','merge.speculative_held','notification.enqueued','notification.failed','notification.sent','phase1.fixture.ci_pending','phase1.fixture.completed','phase1.fixture.failed','phase1.fixture.started','planner.completed','planner.failed','planner.rerequested','planner.started','planner.subtasks.emitted','recovery.inspection_opened','recovery.replan_queued','recovery.revise_routed','recovery.rollback_queued','redaction.raw_access','review.approved','review.auto_approved','review.changes_requested','review.requested','run.completed','run.failed','run.queued','run.started','runner.allocated','runner.failed','runner.released','task.completed','task.failed','task.queued','task.started','usage.accounting.observed','usage.window.observed','usage.window.pressure','workspace.failed','workspace.git_captured','workspace.prepared','writer.completed','writer.failed','writer.started','writer.subtask.completed','writer.subtask.failed','writer.subtask.started'));--> statement-breakpoint

-- CI-intelligence ingestion (foundation) RLS for the per-test results surface,
-- mirroring merge_queue (0045) / post_merge_issue_claims (0049): the table carries
-- its OWN org_id, so it uses the 3a-style DIRECT org match (deny by default; a row
-- is readable/writable only under its own org's scope). The ingest INSERT + the
-- `ci.tests.reported` emit run under runWithOrgScope, so a cross-org write is both
-- unreadable AND denied (42501). Append-only. Idempotent via DROP POLICY IF EXISTS.
ALTER TABLE ci_test_results ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS rls_org_isolation ON ci_test_results;--> statement-breakpoint
CREATE POLICY rls_org_isolation ON ci_test_results FOR ALL
  USING (org_id = current_setting('app.current_org_id', true))
  WITH CHECK (org_id = current_setting('app.current_org_id', true));
