// @generated by scripts/gen-dashboard-types.mjs — DO NOT EDIT BY HAND.
//
// Client-side response types for the orchestrator run-detail HTTP API,
// generated from the neutral JSON-Schema export under contracts/json/http/**
// (itself emitted from the orchestrator's Zod contracts via
// scripts/contract-schema-export.mjs). Regenerate with
// `corepack pnpm run codegen:dashboard-types`; the
// `check:dashboard-types-drift` gate fails if this file diverges from the
// committed JSON Schema. See docs/architecture/future-refactor-and-scale.md §2.

/** Generated from `tanren.http.ProjectFeedItem` (contracts/json/http/ProjectFeedItem.json). */
export interface ProjectFeedItem {
  eventType: string;
  id: number | string;
  payload: unknown;
  projectId: string | null;
  redactedPaths: string[];
  runId: string;
  specId: string | null;
  taskId: string | null;
  ts: string;
}

/** Generated from `tanren.http.RunCostRecord` (contracts/json/http/RunCostRecord.json). */
export interface RunCostRecord {
  billingMode: "per_token" | "subscription" | "self_hosted";
  cacheCreationTokens: number;
  cachedInputTokens: number;
  cli: string;
  costBasis: "ccusage" | "provider_pricing" | "unknown";
  costUsd: string | null;
  id: number | string;
  inputTokens: number;
  model: string;
  outputTokens: number;
  projectId: string;
  provider: string;
  reasoningOutputTokens: number;
  recordedAt: string;
  runId: string;
  taskId: string;
  totalTokens: number;
}

/** Generated from `tanren.http.RunDetail` (contracts/json/http/RunDetail.json). */
export interface RunDetail {
  costs: Array<{
    billingMode: "per_token" | "subscription" | "self_hosted";
    cacheCreationTokens: number;
    cachedInputTokens: number;
    cli: string;
    costBasis: "ccusage" | "provider_pricing" | "unknown";
    costUsd: string | null;
    id: number | string;
    inputTokens: number;
    model: string;
    outputTokens: number;
    projectId: string;
    provider: string;
    reasoningOutputTokens: number;
    recordedAt: string;
    runId: string;
    taskId: string;
    totalTokens: number;
  }>;
  forgeThread: {
    recentTurns: unknown[];
    threadId: string;
  } | null;
  insights: unknown[];
  recentEvents: Array<{
    eventType: string;
    id: number | string;
    payload: unknown;
    projectId: string | null;
    redactedPaths: string[];
    runId: string | null;
    specId: string | null;
    taskId: string | null;
    ts: string;
  }>;
  run: {
    branch: string;
    endedAt: string | null;
    outcome:
      | "hello_complete"
      | "phase1_fixture_complete"
      | "phase2_easy_complete"
      | "phase2_medium_complete"
      | "halted"
      | "escape_hatch_hit"
      | "retry_budget_exhausted"
      | "window_exhausted"
      | "quota_exceeded"
      | "cancelled"
      | "hello_world_complete"
      | "ok"
      | "failed"
      | "pending"
      | null;
    prUrl: string | null;
    projectId: string;
    runId: string;
    specId: string;
    startedAt: string;
    status: "queued" | "running" | "halted" | "completed" | "failed" | "cancelled" | "done";
    trigger: string;
  };
  spec: {
    behaviorIds: string[];
    description: string;
    milestoneId: string | null;
    specId: string;
    title: string;
  };
  tasks: Array<{
    attempt: number;
    cli: string;
    endedAt: string | null;
    failureKind: string | null;
    kind: "plan" | "write" | "check" | "audit" | "ci" | "review" | "merge" | "demo" | "forge";
    model: string | null;
    outcome:
      | "passed"
      | "failed"
      | "rejected_by_checker"
      | "rejected_by_auditor"
      | "timed_out"
      | "crashed"
      | "window_exhausted"
      | "cancelled"
      | "ok"
      | "pending"
      | null;
    parentTaskId: string | null;
    runId: string;
    startedAt: string | null;
    status: "queued" | "claimed" | "running" | "done" | "failed" | "cancelled";
    taskId: string;
    title: string;
  }>;
}

/** Generated from `tanren.http.RunEventRow` (contracts/json/http/RunEventRow.json). */
export interface RunEventRow {
  eventType: string;
  id: number | string;
  payload: unknown;
  projectId: string | null;
  redactedPaths: string[];
  runId: string | null;
  specId: string | null;
  taskId: string | null;
  ts: string;
}

/** Generated from `tanren.http.RunListItem` (contracts/json/http/RunListItem.json). */
export interface RunListItem {
  branch: string;
  costTotalUsd: string;
  endedAt: string | null;
  lastEventAt: string | null;
  needsReview: boolean;
  outcome:
    | "hello_complete"
    | "phase1_fixture_complete"
    | "phase2_easy_complete"
    | "phase2_medium_complete"
    | "halted"
    | "escape_hatch_hit"
    | "retry_budget_exhausted"
    | "window_exhausted"
    | "quota_exceeded"
    | "cancelled"
    | "hello_world_complete"
    | "ok"
    | "failed"
    | "pending"
    | null;
  prUrl: string | null;
  projectId: string;
  runId: string;
  specId: string;
  specTitle: string;
  startedAt: string;
  status: "queued" | "running" | "halted" | "completed" | "failed" | "cancelled" | "done";
  trigger: string;
}

/** Generated from `tanren.http.RunSpecSummary` (contracts/json/http/RunSpecSummary.json). */
export interface RunSpecSummary {
  behaviorIds: string[];
  description: string;
  milestoneId: string | null;
  specId: string;
  title: string;
}

/** Generated from `tanren.http.RunSummary` (contracts/json/http/RunSummary.json). */
export interface RunSummary {
  branch: string;
  endedAt: string | null;
  outcome:
    | "hello_complete"
    | "phase1_fixture_complete"
    | "phase2_easy_complete"
    | "phase2_medium_complete"
    | "halted"
    | "escape_hatch_hit"
    | "retry_budget_exhausted"
    | "window_exhausted"
    | "quota_exceeded"
    | "cancelled"
    | "hello_world_complete"
    | "ok"
    | "failed"
    | "pending"
    | null;
  prUrl: string | null;
  projectId: string;
  runId: string;
  specId: string;
  startedAt: string;
  status: "queued" | "running" | "halted" | "completed" | "failed" | "cancelled" | "done";
  trigger: string;
}

/** Generated from `tanren.http.SseCostsFrame` (contracts/json/http/SseCostsFrame.json). */
export interface SseCostsFrame {
  costs: Array<{
    billingMode: "per_token" | "subscription" | "self_hosted";
    cacheCreationTokens: number;
    cachedInputTokens: number;
    cli: string;
    costBasis: "ccusage" | "provider_pricing" | "unknown";
    costUsd: string | null;
    id: number | string;
    inputTokens: number;
    model: string;
    outputTokens: number;
    projectId: string;
    provider: string;
    reasoningOutputTokens: number;
    recordedAt: string;
    runId: string;
    taskId: string;
    totalTokens: number;
  }>;
}

/** Generated from `tanren.http.SseEventsFrame` (contracts/json/http/SseEventsFrame.json). */
export interface SseEventsFrame {
  events: Array<{
    eventType: string;
    id: number | string;
    payload: unknown;
    projectId: string | null;
    redactedPaths: string[];
    runId: string | null;
    specId: string | null;
    taskId: string | null;
    ts: string;
  }>;
}

/** Generated from `tanren.http.SseHeartbeatFrame` (contracts/json/http/SseHeartbeatFrame.json). */
export interface SseHeartbeatFrame {
  ts: string;
}

/** Generated from `tanren.http.SseStatusFrame` (contracts/json/http/SseStatusFrame.json). */
export interface SseStatusFrame {
  outcome:
    | "hello_complete"
    | "phase1_fixture_complete"
    | "phase2_easy_complete"
    | "phase2_medium_complete"
    | "halted"
    | "escape_hatch_hit"
    | "retry_budget_exhausted"
    | "window_exhausted"
    | "quota_exceeded"
    | "cancelled"
    | "hello_world_complete"
    | "ok"
    | "failed"
    | "pending"
    | null;
  runId: string;
  status: "queued" | "running" | "halted" | "completed" | "failed" | "cancelled" | "done";
}

/** Generated from `tanren.http.TaskTimelineEntry` (contracts/json/http/TaskTimelineEntry.json). */
export interface TaskTimelineEntry {
  attempt: number;
  cli: string;
  endedAt: string | null;
  failureKind: string | null;
  kind: "plan" | "write" | "check" | "audit" | "ci" | "review" | "merge" | "demo" | "forge";
  model: string | null;
  outcome:
    | "passed"
    | "failed"
    | "rejected_by_checker"
    | "rejected_by_auditor"
    | "timed_out"
    | "crashed"
    | "window_exhausted"
    | "cancelled"
    | "ok"
    | "pending"
    | null;
  parentTaskId: string | null;
  runId: string;
  startedAt: string | null;
  status: "queued" | "claimed" | "running" | "done" | "failed" | "cancelled";
  taskId: string;
  title: string;
}
