/**
 * Narrow response types for the orchestrator product APIs the shell consumes.
 *
 * These mirror the JSON shapes returned by the orchestrator routes the shell
 * depends on (orgs, projects, forge tools). They are intentionally local and
 * minimal — the shell only reads the fields it renders. Where the orchestrator
 * contract widens, widen these alongside it (they are not auto-derived).
 */

/** An organization the operator is a member of (`GET /orgs`). */
export interface OrgSummary {
  id: string;
  kind: string;
  login: string;
  displayName: string | null;
  role: string;
}

/** A project within an org (`GET /orgs/:orgId/projects`). */
export interface ProjectSummary {
  projectId: string;
  name: string;
  repoUrl: string;
  defaultBranch: string | null;
  runnerImage: string | null;
  allocator: string | null;
}

/**
 * A single palette item surfaced from the Forge tool surface (P2A-0019).
 * `kind` distinguishes read actions (route in the shell) from write actions
 * (call the operator-button endpoint) and ask-forge prompts (open a thread).
 */
export interface PaletteItem {
  glyph: string;
  kanji?: boolean;
  title: string;
  desc: string;
  /** Read actions carry an in-shell route to navigate to. */
  route?: string;
  /** Write actions carry a Forge tool id invoked via `POST .../forge/tools`. */
  tool?: string;
  /** Optional pre-filled args for a write tool. */
  args?: Record<string, unknown>;
}

/** A named group of palette items (`quick actions`, `forge this`, `ask forge`). */
export interface PaletteGroup {
  group: string;
  items: PaletteItem[];
}

// ---------------------------------------------------------------------------
// P2B-0003 additive contracts — project view, spec creation, routing settings.
// These mirror the orchestrator JSON shapes the project/spec/settings screens
// read (P2A-0013 specs/projects, P2A-0014 runs/feed, P2A-0018 milestones/
// behaviors/personas, P2A-0019 forge turns, P2A-0020 insights, P2A-0006
// routing config). Local + minimal: only the fields these screens render.
// ---------------------------------------------------------------------------

/** A run-list row (`GET /orgs/:orgId/projects/:projectId/runs`, P2A-0014). */
export interface RunListItem {
  runId: string;
  specId: string;
  projectId: string;
  branch: string;
  trigger: string;
  status: string;
  outcome: string | null;
  startedAt: string;
  endedAt: string | null;
  prUrl: string | null;
  specTitle: string;
  costTotalUsd: string;
  lastEventAt: string | null;
  /** True when the run is in a review state with an open PR. */
  needsReview: boolean;
}

/** A project activity-feed event (`GET .../feed`, P2A-0014). */
export interface ProjectFeedItem {
  id: number | string;
  ts: string;
  runId: string;
  taskId: string | null;
  specId: string | null;
  projectId: string | null;
  eventType: string;
  redactedPaths: string[];
}

/** A spec row (`GET .../specs`, P2A-0013). */
export interface SpecSummary {
  specId: string;
  projectId: string;
  title: string;
  description: string;
  acceptanceCriteria: string[];
  dependsOn: string[];
  status: string;
}

/** A milestone row (`GET .../milestones`, P2A-0018). */
export interface MilestoneSummary {
  id: string;
  projectId: string;
  label: string;
  name: string;
  description: string | null;
  orderIndex: number;
  eta: string | null;
  status: string;
}

/** A persona row (`GET .../personas`, P2A-0018). */
export interface PersonaSummary {
  id: string;
  name: string;
  description: string;
}

/** A behavior row (`GET .../behaviors?personaId=`, P2A-0018). */
export interface BehaviorSummary {
  id: string;
  personaId: string;
  title: string;
  description: string | null;
}

/**
 * A workflow-insight (`GET .../insights`, P2A-0020). Only `retry_hotspot`,
 * `model_mismatch`, `pace_anomaly` are surfaced in v0. `payload` carries the
 * kind-specific fields; `actions` carry operator-button tool calls.
 */
export interface InsightSummary {
  id: string;
  kind: "retry_hotspot" | "model_mismatch" | "pace_anomaly";
  projectId: string;
  severity: "info" | "warn" | "fail";
  title: string;
  body: string;
  payload: Record<string, unknown> & { kind: string };
  actions: InsightActionSummary[];
  computedAt: string;
  acknowledgedAt: string | null;
}

/** An operator-button action on an insight — carries a Forge tool call. */
export interface InsightActionSummary {
  label: string;
  /** ForgeToolCall shape `{ tool, args }`. */
  toolCall: { tool: string; args?: Record<string, unknown> };
}

/**
 * The render payload of a Forge narration turn (P2A-0008 `ForgeAnswer`,
 * generated by P2A-0019). `body` is the one-sentence project pulse;
 * `prompts` are the suggested follow-up chips.
 */
export interface ForgeAnswer {
  body: string;
  attentionItems: Array<{
    priority: string;
    title: string;
    sub: string;
    action?: { label: string; toolCall: { tool: string; args?: Record<string, unknown> } };
  }>;
  prompts: string[];
}

// ---- Routing config (P2A-0006) — the project config the settings screen edits.

export type RoleId = "plan" | "write" | "check" | "audit" | "demo" | "forge";
export const ROLE_IDS: RoleId[] = ["plan", "write", "check", "audit", "demo", "forge"];
export type HealthHint = "ok" | "warn" | "rate_limited" | "fail";

/** One fallback step in a role's routing chain. */
export interface RoutingChainEntry {
  cli: string;
  model: string;
  authRef: string;
  healthHint?: HealthHint;
}

export interface RoutingChain {
  chain: RoutingChainEntry[];
}

export type RoutingTable = Record<RoleId, RoutingChain>;

export interface EscapeHatches {
  maxWriterIterPerSubtask: number;
  maxPlannerRerunsPerSpec: number;
  maxRetriesPerTransientFailure: number;
  maxSpecDiscoveryRoundsWithForge: number;
}

/** A project's full versioned config (`GET .../projects/:projectId` → `config`). */
export interface ProjectConfig {
  version: 1;
  routing: RoutingTable;
  escapeHatches: Partial<EscapeHatches>;
  governancePosture?: string;
  mergeIntegration?: string;
  [key: string]: unknown;
}

/** A project with its merged config (`GET .../projects/:projectId`, P2A-0013). */
export interface ProjectDetail {
  projectId: string;
  name: string;
  repoUrl: string;
  defaultBranch: string | null;
  runnerImage: string | null;
  allocator: string | null;
  config: ProjectConfig;
}

// ── P2B-0002 onboarding / credentials / notifications additions ──────────
// All additive: read the fields the onboarding/credentials/notifications
// screens render off the P2A-0013 (doctor/credentials/brownfield) and
// P2A-0017 (notifications) contracts. Local + minimal, like the rest.

/** A single `/doctor` check (P2A-0013 DoctorCheck). */
export interface DoctorCheck {
  name: string;
  status: "ok" | "warn" | "fail";
  detail: string;
  latencyMs: number | null;
}

/** `/doctor` report (P2A-0013 DoctorReport). */
export interface DoctorReport {
  ok: boolean;
  checks: DoctorCheck[];
  generatedAt: string;
}

/** A credential reference record (P2A-0013 CredentialRecord). Never a value. */
export interface CredentialRecord {
  ref: string;
  kind: "codex_chatgpt_auth" | "github_token" | "opaque";
  scope: "org" | "me";
  ownerId: string;
  createdAt: string;
}

/** A detected (read-only, never written) target-repo file (P2A-0013). */
export interface BrownfieldDetectedFile {
  path: string;
  present: boolean;
  size?: number;
  preview?: string;
}

/** Result of the brownfield link call (P2A-0013). */
export interface BrownfieldLinkResult {
  projectId: string;
  repoUrl: string;
  orgId: string;
  detectedFiles: BrownfieldDetectedFile[];
  writesPerformed: number;
}

/** A created project (P2A-0013 project create). */
export interface CreatedProject {
  projectId: string;
  name: string;
  repoUrl: string;
  defaultBranch: string | null;
  runnerImage: string | null;
  allocator: string | null;
}

/** P2A-0017 notification channel kinds. */
export type ChannelKind =
  | "ntfy"
  | "slack"
  | "github_checks"
  | "teams"
  | "discord"
  | "email"
  | "twilio"
  | "pagerduty"
  | "webhook";

/** P2A-0017 severity taxonomy. */
export type Severity = "ok" | "info" | "warn" | "fail";

/** A configured notification destination (P2A-0017 NotificationTargetRow). */
export interface NotificationTarget {
  id: string;
  orgId: string;
  scope: "org" | "user";
  userId: string | null;
  channelKind: ChannelKind;
  destination: string;
  label: string;
  enabled: boolean;
  weekendMute: boolean;
}

/** A per-(target × event) opt-in (P2A-0017 NotificationRouteRow). */
export interface NotificationRoute {
  id: string;
  targetId: string;
  eventName: string;
  enabled: boolean;
  minSeverity: Severity;
}

/** An event-registry row + its default severity, for the matrix rows. */
export interface NotificationEvent {
  eventName: string;
  defaultSeverity: Severity;
}

/** The full notifications-matrix payload the screen renders against. */
export interface NotificationMatrix {
  targets: NotificationTarget[];
  routes: NotificationRoute[];
  events: NotificationEvent[];
}
