packages:
  - "cli"
  - "db"
  - "services/*"

onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - ssh2
allowBuilds:
  cpu-features: true
  esbuild: true
  lefthook: true
  protobufjs: false
  ssh2: true
