// Track C §3 of docs/architecture/portability-and-longevity.md — the unified
// JSON-Schema export catalog. This module is the SINGLE place that enumerates
// every Zod-defined contract the project wants emitted as a language-neutral
// JSON Schema artifact (the source a future Rust port generates serde types
// from). It imports only Zod schemas already authored elsewhere; it does not
// re-author any shape.
//
// The committed JSON mirror under `contracts/json/**` is regenerated by
// `scripts/contract-schema-export.mjs` and pinned against drift by the
// `check:contract-schema-drift` gate (mirroring the answerer-schema-drift
// mechanism). Adding a contract is one entry in one of the lists below.
//
// We deliberately reuse Zod 4's native `z.toJSONSchema` (the same renderer the
// answerer export uses) rather than introducing a separate zod-to-json-schema
// dependency.

import { z, type ZodType } from "zod";

import { EventRegistry } from "../events/registry.js";
import { IntegrationsManifestV1Schema } from "../integrations/manifest/schema.js";
import { stateEnumCatalog } from "../state/index.js";
import { answererSchemaCatalog } from "../answerers/schemas/catalog.js";
import { InsightPayload } from "../insights/types.js";
import { integrationReadContractCatalog } from "../../routes/integrations/contract.js";
import {
  RunDetail,
  RunListItem,
  RunLocation,
  RunSummary,
  RunSpecSummary,
  RunCostRecord,
  OrgCosts,
  RunEventRow,
  TaskTimelineEntry,
  ProjectFeedItem,
  SseStatusFrame,
  SseEventsFrame,
  SseCostsFrame,
  SseHeartbeatFrame,
} from "../../routes/runs/contract.js";

// A single contract entry: the JSON file to emit (relative to contracts/json),
// a stable schema id embedded in the artifact, and the Zod source schema.
export interface ContractSchemaDescriptor {
  readonly family: string;
  readonly generatedFile: string;
  readonly schemaId: string;
  readonly zod: ZodType;
}

function entry(family: string, name: string, schemaId: string, zod: ZodType): ContractSchemaDescriptor {
  return { family, generatedFile: `${family}/${name}.json`, schemaId, zod };
}

// --- Event payloads ---------------------------------------------------------
// One JSON Schema per registered event name, keyed by the event name with dots
// turned into a path-safe filename. The source of truth is the EventRegistry.
const eventEntries: ContractSchemaDescriptor[] = Object.entries(EventRegistry).map(([eventName, schema]) =>
  entry("events", eventName.replaceAll(".", "_"), `tanren.event.${eventName}`, schema as ZodType),
);

// --- State enums ------------------------------------------------------------
// Each state enum exported as a JSON Schema `enum` so the Rust port derives the
// same closed string sets the DB CHECK constraints enforce.
const stateEntries: ContractSchemaDescriptor[] = Object.entries(stateEnumCatalog).map(([name, descriptor]) =>
  entry("state", name, `tanren.state.${name}`, z.enum(descriptor.values as [string, ...string[]])),
);

// --- Answerer schemas (already JSON-exported elsewhere; mirrored here so the
// unified contracts/json tree is the one place a port reads from). -----------
const answererEntries: ContractSchemaDescriptor[] = Object.values(answererSchemaCatalog).map((d) =>
  entry("answerers", d.role, d.schemaId, d.zod),
);

// --- HTTP request/response (run-detail read API — the frozen contract the
// dashboard consumes; see routes/runs/contract.ts). --------------------------
const httpEntries: ContractSchemaDescriptor[] = [
  entry("http", "RunDetail", "tanren.http.RunDetail", RunDetail),
  entry("http", "RunListItem", "tanren.http.RunListItem", RunListItem),
  entry("http", "RunLocation", "tanren.http.RunLocation", RunLocation),
  entry("http", "RunSummary", "tanren.http.RunSummary", RunSummary),
  entry("http", "RunSpecSummary", "tanren.http.RunSpecSummary", RunSpecSummary),
  entry("http", "RunCostRecord", "tanren.http.RunCostRecord", RunCostRecord),
  entry("http", "OrgCosts", "tanren.http.OrgCosts", OrgCosts),
  entry("http", "RunEventRow", "tanren.http.RunEventRow", RunEventRow),
  entry("http", "TaskTimelineEntry", "tanren.http.TaskTimelineEntry", TaskTimelineEntry),
  entry("http", "ProjectFeedItem", "tanren.http.ProjectFeedItem", ProjectFeedItem),
  entry("http", "SseStatusFrame", "tanren.http.SseStatusFrame", SseStatusFrame),
  entry("http", "SseEventsFrame", "tanren.http.SseEventsFrame", SseEventsFrame),
  entry("http", "SseCostsFrame", "tanren.http.SseCostsFrame", SseCostsFrame),
  entry("http", "SseHeartbeatFrame", "tanren.http.SseHeartbeatFrame", SseHeartbeatFrame),
];

// --- Workflow insights ------------------------------------------------------
const insightEntries: ContractSchemaDescriptor[] = [
  entry("insights", "InsightPayload", "tanren.insights.InsightPayload", InsightPayload),
];

// --- Integration manifest ---------------------------------------------------
// The `.tanren/integrations.yml` per-project manifest contract (in-8), emitted as a
// language-neutral JSON Schema artifact the same way every other Zod contract is.
const integrationEntries: ContractSchemaDescriptor[] = [
  entry(
    "integrations",
    "IntegrationsManifestV1",
    "tanren.integrations.IntegrationsManifestV1",
    IntegrationsManifestV1Schema,
  ),
];

// --- Integration HTTP read surface (in-20) -----------------------------------
// The five versioned response contracts the GET-only `/v1/orgs/.../integrations/*`
// surface publishes (lifecycle inventory, integration requirements, capability
// nodes, bindings with the in-15 appEnvHash proof, delivery-DAG status). These
// mirror `routes/runtimeVerification/contract.ts` (rv-22): each is a `.strict()`
// Zod object with a frozen `version: z.literal("v1")` tag, and the source of
// truth lives in `routes/integrations/contract.ts`. They are registered in the
// unified `contracts/json/integrations/**` tree so a Rust port reads them
// alongside every other contract; the SEMANTIC compat floor under
// `contracts/integration-read-compat/v1.json` (mirroring the rv-read-compat
// guard) is the consumer-facing layer that allows additive growth.
const integrationReadEntries: ContractSchemaDescriptor[] = integrationReadContractCatalog.map((d) =>
  entry("integrations", d.name, d.schemaId, d.zod),
);

// The full catalog, sorted by generatedFile so the emitted tree and any diff is
// stable regardless of declaration order above.
export const contractSchemaCatalog: ReadonlyArray<ContractSchemaDescriptor> = [
  ...eventEntries,
  ...stateEntries,
  ...answererEntries,
  ...httpEntries,
  ...insightEntries,
  ...integrationEntries,
  ...integrationReadEntries,
].sort((a, b) => a.generatedFile.localeCompare(b.generatedFile));

// renderContractJsonSchema is the single chokepoint converting a Zod source
// schema to the JSON Schema shape. It mirrors renderAnswererJsonSchema but adds
// two coercions so the broader contract surface (which includes HTTP shapes)
// renders fully:
//   - unrepresentable: "any" — Zod constructs that have no JSON Schema form
//     (e.g. z.coerce.date()) emit `{}` instead of throwing, so a single
//     unrepresentable field never blocks the whole export.
//   - override — z.date() / z.coerce.date() become { type: "string", format:
//     "date-time" }, which is how they cross the wire as JSON anyway and is the
//     shape a Rust port maps to a chrono::DateTime.
export function renderContractJsonSchema(zodSchema: ZodType): Record<string, unknown> {
  return z.toJSONSchema(zodSchema, {
    target: "draft-2020-12",
    unrepresentable: "any",
    override: (ctx) => {
      if (ctx.zodSchema instanceof z.ZodDate) {
        ctx.jsonSchema.type = "string";
        ctx.jsonSchema.format = "date-time";
      }
    },
  }) as Record<string, unknown>;
}
