// ds-2 — deterministic web projections for a resolved DTCG token set.

import type { DtcgResolution, DtcgValue, ResolvedDtcgToken } from "./dtcgResolver.js";

export interface WebTokenBinding {
  readonly path: string;
  readonly cssVariable: string;
  readonly cssValue: string;
  readonly type?: string;
}

export interface WebTokenProjection {
  readonly tokens: readonly WebTokenBinding[];
  readonly css: string;
  readonly tailwindConfig: string;
  readonly dtcgExport: string;
  readonly resolverExport: string;
}

/** A resolved token that cannot safely become a CSS custom property fails closed. */
export class WebTokenProjectionError extends Error {
  constructor(
    readonly path: string,
    readonly issue: string,
  ) {
    super(`web token '${path}' cannot be projected: ${issue}`);
    this.name = "WebTokenProjectionError";
  }
}

/** Resolve DTCG values into deterministic CSS/Tailwind/DTCG export source. */
export function projectWebTokens(resolution: DtcgResolution): WebTokenProjection {
  const tokens = resolution.tokens.map(toBinding);
  assertUnique(tokens, (token) => token.cssVariable, "CSS custom property");
  assertUnique(tokens, (token) => token.path, "token path");
  assertCatalogMinimum(tokens);
  return {
    tokens,
    css: renderCss(tokens),
    tailwindConfig: renderTailwindConfig(tokens),
    dtcgExport: renderDtcgExport(resolution.tokens),
    resolverExport: renderResolverExport(resolution, tokens),
  };
}

function toBinding(token: ResolvedDtcgToken): WebTokenBinding {
  const path = token.path.join(".");
  return {
    path,
    cssVariable: `--tanren-${token.path.map(cssSegment).join("-")}`,
    cssValue: cssValue(token.value, path),
    ...(token.type !== undefined && { type: token.type }),
  };
}

function cssSegment(segment: string): string {
  return Array.from(segment)
    .map((character) =>
      /^[A-Za-z0-9_-]$/u.test(character) ? character : `u${character.codePointAt(0)?.toString(16)}-`,
    )
    .join("");
}

function cssValue(value: DtcgValue, path: string): string {
  if (typeof value === "string" || typeof value === "number") return String(value);
  if (isDimension(value)) return `${value.value}${value.unit}`;
  if (Array.isArray(value) && value.every((item) => typeof item === "string" || typeof item === "number")) {
    return value.join(" ");
  }
  throw new WebTokenProjectionError(path, "expected a CSS scalar, a { value, unit } dimension, or a scalar list");
}

function isDimension(value: DtcgValue): value is { readonly value: number; readonly unit: string } {
  return (
    isRecord(value) &&
    typeof value["value"] === "number" &&
    Number.isFinite(value["value"]) &&
    typeof value["unit"] === "string" &&
    value["unit"].length > 0
  );
}

function assertCatalogMinimum(tokens: readonly WebTokenBinding[]): void {
  if (!tokens.some((token) => token.type === "color")) {
    throw new WebTokenProjectionError("<catalog>", "a web catalog requires at least one resolved color token");
  }
  if (!tokens.some((token) => token.type === "dimension")) {
    throw new WebTokenProjectionError("<catalog>", "a web catalog requires at least one resolved dimension token");
  }
}

function assertUnique(
  tokens: readonly WebTokenBinding[],
  keyOf: (token: WebTokenBinding) => string,
  label: string,
): void {
  const seen = new Set<string>();
  for (const token of tokens) {
    const key = keyOf(token);
    if (seen.has(key)) throw new WebTokenProjectionError(token.path, `duplicates ${label} '${key}'`);
    seen.add(key);
  }
}

function renderCss(tokens: readonly WebTokenBinding[]): string {
  return [
    "/* Generated by Tanren's web design adapter. Do not edit by hand. */",
    ":root {",
    ...tokens.map((token) => `  ${token.cssVariable}: ${token.cssValue};`),
    "}",
    "",
  ].join("\n");
}

function renderTailwindConfig(tokens: readonly WebTokenBinding[]): string {
  const groups: Record<string, Record<string, string>> = {};
  for (const token of tokens) {
    const group = tailwindGroup(token.type);
    if (group === undefined) continue;
    const entries = groups[group] ?? {};
    entries[tailwindKey(token.path)] = `var(${token.cssVariable})`;
    groups[group] = entries;
  }
  return [
    'import type { Config } from "tailwindcss";',
    "",
    "const config = {",
    '  content: ["./src/**/*.{ts,tsx,js,jsx}"],',
    "  theme: { extend: " + JSON.stringify(groups, null, 2).replaceAll("\n", "\n  ") + " },",
    "  plugins: [],",
    "} satisfies Config;",
    "",
    "export default config;",
    "",
  ].join("\n");
}

function tailwindGroup(type: string | undefined): string | undefined {
  switch (type) {
    case "color":
      return "colors";
    case "dimension":
      return "spacing";
    case "fontWeight":
      return "fontWeight";
    case "fontFamily":
      return "fontFamily";
    default:
      return undefined;
  }
}

function tailwindKey(path: string): string {
  return path.replaceAll(".", "-");
}

function renderDtcgExport(tokens: readonly ResolvedDtcgToken[]): string {
  const root: Record<string, unknown> = {
    $schema: "https://design-tokens.github.io/community-group/format/",
  };
  for (const token of tokens) {
    let cursor = root;
    for (const segment of token.path.slice(0, -1)) {
      const current = cursor[segment];
      if (isRecord(current)) {
        cursor = current;
      } else {
        const next: Record<string, unknown> = {};
        cursor[segment] = next;
        cursor = next;
      }
    }
    const leaf: Record<string, unknown> = { $value: canonicalize(token.value) };
    if (token.type !== undefined) leaf["$type"] = token.type;
    cursor[token.path.at(-1) ?? ""] = leaf;
  }
  return `${JSON.stringify(root, null, 2)}\n`;
}

function renderResolverExport(resolution: DtcgResolution, tokens: readonly WebTokenBinding[]): string {
  return `${JSON.stringify(
    {
      schemaVersion: 1,
      mode: resolution.mode,
      tokens: tokens.map((token) => ({
        path: token.path,
        cssVariable: token.cssVariable,
        ...(token.type !== undefined && { type: token.type }),
      })),
    },
    null,
    2,
  )}\n`;
}

function canonicalize(value: DtcgValue): DtcgValue {
  if (Array.isArray(value)) return value.map((item) => canonicalize(item));
  if (isRecord(value)) {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, item]) => [key, canonicalize(item)]),
    );
  }
  return value;
}

function isRecord(value: unknown): value is Record<string, DtcgValue> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
