// P3-0016: the config-injection PR. From a confirmed recon report + the chosen
// governance posture, propose the integration files, let the operator EXCLUDE
// any, then open ONE PR in the target repo that adds the kept files. "No runs
// until merged" — opening the PR performs the only writes brownfield onboarding
// ever makes, and the run loop stays gated on the merge. Tanren's native merge
// queue (P2d) drives the merge directly, so no external merge-queue config is
// injected — only the CI gate, CODEOWNERS, and the project snapshot land.
//
// The GitHub side is an injectable `ConfigInjectionGitHub` port (same shape as
// the P3-0017 `ConfigGateGitHub`): production wires the App-token-backed adapter
// (`githubConfigInjection.ts`), tests inject a fake that records the committed
// files + returns a synthetic PR. No new entity, no migration — the files land
// in the target repo via a PR, not in our database.

import type { GovernancePosture } from "../../config/shared.js";
import type { ReconReport } from "./types.js";

// The six files the config-injection PR proposes. `path` is the repo path;
// `kind` tags the snapshot file specially (regenerated only via the audit gate).
export interface ProposedFile {
  path: string;
  content: string;
  addedLines: number;
  /** The `.tanren/PROJECT.md` one-time snapshot (don't-edit-by-hand). */
  snapshot?: boolean;
}

export interface ProposeFilesInput {
  repoSlug: string;
  orgLogin: string;
  repoUrl: string;
  report: ReconReport;
  posture: GovernancePosture;
  generatedAt: string;
  /** The owner team for CODEOWNERS scaffolding (defaults from the org login). */
  operatorsTeam?: string;
}

function postureLine(posture: GovernancePosture): string {
  if (posture === "open") return "open — humans + tanren both push · external pushes tracked, not blocked";
  if (posture === "audit_only") return "audit-only — tanren observes · opens no PRs · operator promotes findings";
  return "strict — every change goes through a spec · external pushes warned + auto-spec'd";
}

function projectSnapshot(input: ProposeFilesInput): string {
  const personas =
    input.report.personas.map((p) => `- **${p.name}** — ${p.description}`).join("\n") || "- (none inferred)";
  const behaviors = input.report.behaviors.map((b) => `- ${b.persona} · ${b.title}`).join("\n") || "- (none inferred)";
  const architecture =
    input.report.architecture.map((a) => `- **${a.layer}** · ${a.detail}`).join("\n") || "- (unknown)";
  return `# ${input.repoSlug}

> Generated by tanren at onboarding · ${input.generatedAt}
> Source of truth: orchestrator dashboard · /projects/${input.repoSlug}
> Don't edit by hand — regenerated only via the audit gate.

## identity

- **org** · ${input.orgLogin}
- **repo** · ${input.repoUrl}
- **purpose** · ${input.report.identity.purpose}

## personas

${personas}

## behaviors

${behaviors}

## architecture

${architecture}

## merge posture

- ${postureLine(input.posture)}
- codeowner review required
`;
}

const TANREN_CI_YAML = `# tanren-ci.yml — added by tanren config-injection (P3-0016)
name: tanren-ci
on:
  pull_request:
    branches: [main]
jobs:
  tanren-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: corepack pnpm install --frozen-lockfile
      - name: lint
        run: corepack pnpm run lint
      - name: typecheck
        run: corepack pnpm run typecheck
      # Emit a JUnit report so Tanren can ingest PER-TEST results (CI-intelligence).
      # Capture the test step's exit code separately: a runner that crashes AFTER
      # writing a clean-looking report must NOT be read as all-green (the
      # silent-failure guard) — \`--test-exit-code\` is uploaded alongside the XML.
      #   vitest: --reporter=junit --outputFile (shown below)
      #   pytest: --junitxml=reports/junit.xml
      #   go:     gotestsum --junitfile reports/junit.xml
      - name: test
        id: test
        run: |
          mkdir -p reports
          set +e
          corepack pnpm run test -- --reporter=junit --outputFile=reports/junit.xml
          echo "exit_code=$?" >> "$GITHUB_OUTPUT"
          set -e
      # Upload the report(s) + the test-step outcome to Tanren's ingest endpoint,
      # HMAC-signed with the CI ingest signing key already propagated as an Actions
      # secret (\`TANREN_RUN_TOKEN\`) — the SAME secret the ingest endpoint validates
      # against (the per-installation CI-webhook signing secret). The endpoint keys
      # off \`runId\` in the BODY, so the run id is the PR's run branch (\`tanren/<runId>\`)
      # — no per-run secret. Runs on success OR failure so a failing/flaky run is
      # still ingested. The whole step is GATED on both repo-level secrets being
      # present (CI-intelligence is propagated): when CI-intel is NOT configured the
      # step is a clear no-op, never a silent auth failure.
      - name: upload-junit
        if: (success() || failure()) && env.TANREN_INGEST_URL != '' && env.TANREN_RUN_TOKEN != ''
        env:
          TANREN_INGEST_URL: \${{ secrets.TANREN_INGEST_URL }}
          TANREN_RUN_TOKEN: \${{ secrets.TANREN_RUN_TOKEN }}
          # The run id is the PR head branch with the \`tanren/\` prefix stripped
          # (the run's PR branch is \`tanren/<runId>\`); empty for a non-run branch.
          TANREN_HEAD_REF: \${{ github.head_ref }}
        run: |
          python3 - <<'PY'
          import hashlib, hmac, json, os, sys, urllib.request
          head_ref = os.environ.get("TANREN_HEAD_REF", "")
          run_id = head_ref[len("tanren/"):] if head_ref.startswith("tanren/run_") else ""
          if run_id == "":
              print("upload-junit: PR head ref is not a tanren run branch; skipping ingest")
              sys.exit(0)
          reports = []
          for path in ("reports/junit.xml",):
              if os.path.exists(path):
                  with open(path, "r", encoding="utf-8") as fh:
                      reports.append(fh.read())
          body = json.dumps({
              "runId": run_id,
              "headSha": os.environ.get("GITHUB_SHA", ""),
              "attempt": int(os.environ.get("GITHUB_RUN_ATTEMPT", "1")),
              "testExitCode": int("\${{ steps.test.outputs.exit_code }}" or "0"),
              "reports": reports,
          }).encode("utf-8")
          sig = hmac.new(os.environ["TANREN_RUN_TOKEN"].encode("utf-8"), body, hashlib.sha256).hexdigest()
          req = urllib.request.Request(
              os.environ["TANREN_INGEST_URL"] + "/webhooks/ci/junit",
              data=body,
              headers={"content-type": "application/json", "x-hub-signature-256": "sha256=" + sig},
          )
          with urllib.request.urlopen(req) as resp:
              print(resp.status, resp.read().decode("utf-8"))
          PY
      - name: build
        run: corepack pnpm run build
`;

function codeowners(team: string): string {
  return `# CODEOWNERS — scaffolded by tanren config-injection (P3-0016)
* @${team}
.tanren/** @${team}
.github/** @${team}
`;
}

function countLines(content: string): number {
  return content.split("\n").length;
}

/**
 * Build the proposed integration files from the recon report + posture. The
 * order matches the hi-fi file column. `excludePaths` removes any the operator
 * unchecked before the PR is opened.
 */
export function proposeConfigFiles(input: ProposeFilesInput, excludePaths: ReadonlyArray<string> = []): ProposedFile[] {
  const team = input.operatorsTeam ?? `${input.orgLogin}/tanren-operators`;
  const snapshot = projectSnapshot(input);
  const all: ProposedFile[] = [
    {
      path: ".tanren/PROJECT.md",
      content: snapshot,
      addedLines: countLines(snapshot),
      snapshot: true,
    },
    {
      path: ".github/workflows/tanren-ci.yml",
      content: TANREN_CI_YAML,
      addedLines: countLines(TANREN_CI_YAML),
    },
    { path: "CODEOWNERS", content: codeowners(team), addedLines: countLines(codeowners(team)) },
    {
      path: ".gitignore",
      content: "\n# tanren\n.tanren/cache/\n",
      addedLines: 3,
    },
    {
      path: ".github/PULL_REQUEST_TEMPLATE.md",
      content: "## summary\n\n## spec\n\n<!-- tanren spec link -->\n",
      addedLines: 4,
    },
  ];
  const excluded = new Set(excludePaths);
  return all.filter((file) => !excluded.has(file.path));
}

// ── The injectable GitHub side (open-the-PR) ───────────────────────────────

export interface InjectedConfigPullRequest {
  number: number;
  url: string;
  branch: string;
  filesCommitted: ReadonlyArray<string>;
}

// Port the engine opens the PR through. Production wires the App-backed adapter;
// tests inject a fake. Mirrors the P3-0017 `ConfigGateGitHub` seam.
export interface ConfigInjectionGitHub {
  openConfigInjectionPr(input: {
    repoUrl: string;
    baseBranch: string;
    headBranch: string;
    title: string;
    body: string;
    files: ReadonlyArray<{ path: string; content: string }>;
  }): Promise<InjectedConfigPullRequest>;
}

export interface OpenConfigInjectionInput {
  github: ConfigInjectionGitHub;
  repoUrl: string;
  baseBranch: string;
  files: ProposedFile[];
  /** Override the head branch (default `tanren/integrate`). */
  headBranch?: string;
}

const DEFAULT_HEAD_BRANCH = "tanren/integrate";

/**
 * Open the config-injection PR with the KEPT files. The body states the
 * "no runs until merged" contract so the operator (and any reviewer) sees it.
 */
export async function openConfigInjectionPr(input: OpenConfigInjectionInput): Promise<InjectedConfigPullRequest> {
  if (input.files.length === 0) {
    throw new Error("config-injection PR needs at least one file (all were excluded)");
  }
  const headBranch = input.headBranch ?? DEFAULT_HEAD_BRANCH;
  const fileList = input.files.map((f) => `- \`${f.path}\``).join("\n");
  const body = [
    "Tanren integration files, proposed from the read-only recon pass.",
    "",
    "**No runs happen until this PR is merged.** Comment, edit, or close like any other PR.",
    "",
    "Files:",
    fileList,
  ].join("\n");
  return input.github.openConfigInjectionPr({
    repoUrl: input.repoUrl,
    baseBranch: input.baseBranch,
    headBranch,
    title: "tanren · integration config",
    body,
    files: input.files.map((f) => ({ path: f.path, content: f.content })),
  });
}
