// P3-0016: the config-injection PR. From a confirmed recon report + the chosen
// governance posture, propose the 6 integration files, let the operator EXCLUDE
// any, then open ONE PR in the target repo that adds the kept files. "No runs
// until merged" — opening the PR performs the only writes brownfield onboarding
// ever makes, and the run loop stays gated on the merge.
//
// The GitHub side is an injectable `ConfigInjectionGitHub` port (same shape as
// the P3-0017 `ConfigGateGitHub`): production wires the App-token-backed adapter
// (`githubConfigInjection.ts`), tests inject a fake that records the committed
// files + returns a synthetic PR. No new entity, no migration — the files land
// in the target repo via a PR, not in our database.

import type { GovernancePosture } from "../../config/shared.js";
import type { ReconReport } from "./types.js";

// The six files the config-injection PR proposes. `path` is the repo path;
// `kind` tags the snapshot file specially (regenerated only via the audit gate).
export interface ProposedFile {
  path: string;
  content: string;
  addedLines: number;
  /** The `.tanren/PROJECT.md` one-time snapshot (don't-edit-by-hand). */
  snapshot?: boolean;
}

export interface ProposeFilesInput {
  repoSlug: string;
  orgLogin: string;
  repoUrl: string;
  report: ReconReport;
  posture: GovernancePosture;
  generatedAt: string;
  /** The owner team for CODEOWNERS scaffolding (defaults from the org login). */
  operatorsTeam?: string;
}

function postureLine(posture: GovernancePosture): string {
  if (posture === "open") return "open — humans + tanren both push · external pushes tracked, not blocked";
  if (posture === "audit_only") return "audit-only — tanren observes · opens no PRs · operator promotes findings";
  return "strict — every change goes through a spec · external pushes warned + auto-spec'd";
}

function projectSnapshot(input: ProposeFilesInput): string {
  const personas =
    input.report.personas.map((p) => `- **${p.name}** — ${p.description}`).join("\n") || "- (none inferred)";
  const behaviors = input.report.behaviors.map((b) => `- ${b.persona} · ${b.title}`).join("\n") || "- (none inferred)";
  const architecture =
    input.report.architecture.map((a) => `- **${a.layer}** · ${a.detail}`).join("\n") || "- (unknown)";
  return `# ${input.repoSlug}

> Generated by tanren at onboarding · ${input.generatedAt}
> Source of truth: orchestrator dashboard · /projects/${input.repoSlug}
> Don't edit by hand — regenerated only via the audit gate.

## identity

- **org** · ${input.orgLogin}
- **repo** · ${input.repoUrl}
- **purpose** · ${input.report.identity.purpose}

## personas

${personas}

## behaviors

${behaviors}

## architecture

${architecture}

## merge posture

- ${postureLine(input.posture)}
- codeowner review required
`;
}

const TANREN_CI_YAML = `# tanren-ci.yml — added by tanren config-injection (P3-0016)
name: tanren-ci
on:
  pull_request:
    branches: [main]
jobs:
  tanren-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: corepack pnpm install --frozen-lockfile
      - name: lint
        run: corepack pnpm run lint
      - name: typecheck
        run: corepack pnpm run typecheck
      - name: test
        run: corepack pnpm run test
      - name: build
        run: corepack pnpm run build
`;

const MERGIFY_YAML = `# .mergify.yml — added by tanren config-injection (P3-0016)
queue_rules:
  - name: default
    conditions:
      - check-success=tanren-gate
pull_request_rules:
  - name: tanren auto-queue when green + approved
    conditions:
      - check-success=tanren-gate
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
`;

function codeowners(team: string): string {
  return `# CODEOWNERS — scaffolded by tanren config-injection (P3-0016)
* @${team}
.tanren/** @${team}
.github/** @${team}
`;
}

function countLines(content: string): number {
  return content.split("\n").length;
}

/**
 * Build the 6 proposed integration files from the recon report + posture. The
 * order matches the hi-fi file column. `excludePaths` removes any the operator
 * unchecked before the PR is opened.
 */
export function proposeConfigFiles(input: ProposeFilesInput, excludePaths: ReadonlyArray<string> = []): ProposedFile[] {
  const team = input.operatorsTeam ?? `${input.orgLogin}/tanren-operators`;
  const snapshot = projectSnapshot(input);
  const all: ProposedFile[] = [
    {
      path: ".tanren/PROJECT.md",
      content: snapshot,
      addedLines: countLines(snapshot),
      snapshot: true,
    },
    {
      path: ".github/workflows/tanren-ci.yml",
      content: TANREN_CI_YAML,
      addedLines: countLines(TANREN_CI_YAML),
    },
    { path: ".mergify.yml", content: MERGIFY_YAML, addedLines: countLines(MERGIFY_YAML) },
    { path: "CODEOWNERS", content: codeowners(team), addedLines: countLines(codeowners(team)) },
    {
      path: ".gitignore",
      content: "\n# tanren\n.tanren/cache/\n",
      addedLines: 3,
    },
    {
      path: ".github/PULL_REQUEST_TEMPLATE.md",
      content: "## summary\n\n## spec\n\n<!-- tanren spec link -->\n",
      addedLines: 4,
    },
  ];
  const excluded = new Set(excludePaths);
  return all.filter((file) => !excluded.has(file.path));
}

// ── The injectable GitHub side (open-the-PR) ───────────────────────────────

export interface InjectedConfigPullRequest {
  number: number;
  url: string;
  branch: string;
  filesCommitted: ReadonlyArray<string>;
}

// Port the engine opens the PR through. Production wires the App-backed adapter;
// tests inject a fake. Mirrors the P3-0017 `ConfigGateGitHub` seam.
export interface ConfigInjectionGitHub {
  openConfigInjectionPr(input: {
    repoUrl: string;
    baseBranch: string;
    headBranch: string;
    title: string;
    body: string;
    files: ReadonlyArray<{ path: string; content: string }>;
  }): Promise<InjectedConfigPullRequest>;
}

export interface OpenConfigInjectionInput {
  github: ConfigInjectionGitHub;
  repoUrl: string;
  baseBranch: string;
  files: ProposedFile[];
  /** Override the head branch (default `tanren/integrate`). */
  headBranch?: string;
}

const DEFAULT_HEAD_BRANCH = "tanren/integrate";

/**
 * Open the config-injection PR with the KEPT files. The body states the
 * "no runs until merged" contract so the operator (and any reviewer) sees it.
 */
export async function openConfigInjectionPr(input: OpenConfigInjectionInput): Promise<InjectedConfigPullRequest> {
  if (input.files.length === 0) {
    throw new Error("config-injection PR needs at least one file (all were excluded)");
  }
  const headBranch = input.headBranch ?? DEFAULT_HEAD_BRANCH;
  const fileList = input.files.map((f) => `- \`${f.path}\``).join("\n");
  const body = [
    "Tanren integration files, proposed from the read-only recon pass.",
    "",
    "**No runs happen until this PR is merged.** Comment, edit, or close like any other PR.",
    "",
    "Files:",
    fileList,
  ].join("\n");
  return input.github.openConfigInjectionPr({
    repoUrl: input.repoUrl,
    baseBranch: input.baseBranch,
    headBranch,
    title: "tanren · integration config",
    body,
    files: input.files.map((f) => ({ path: f.path, content: f.content })),
  });
}
