// Auditor Answerer output schema. Source of truth for the JSON Schema used
// by `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/audit.json` and is regenerated by
// `scripts/answerer-schema-export.ts`.
//
// SPEC-LOOP REDESIGN (docs/roadmap/spec-loop-redesign.md): the auditor is
// FINDINGS-ONLY. The model emits an explicit `findings: Finding[]`, each with an
// EXPLICIT `severity: P0|P1|P2|P3`, and renders NO verdict. The legacy
// `passed`/`reasoning`/`outstandingBehaviorIds`/`recommendedAction` fields are
// DELETED — the agent must not emit a pass/fail/halt judgment. ALL routing is
// deterministic from the finding severities (the loop's TRIAGE + CONVERGENCE stages
// and the per-project `auditPosture` policy own that, never the model).
//
// `findings` is REQUIRED — NO `.default([])`. A genuinely audited-clean answer emits an
// EXPLICIT `findings: []`; an answer that OMITS findings FAILS TO PARSE (loud), so no
// `auditor.verdict` event is recorded and the run is treated as UN-AUDITED → fail-closed
// P0 at the land.
import { z } from "zod";

export const AUDIT_ANSWER_SCHEMA_ID = "tanren.audit_answer.v3" as const;

// The explicit P0–P3 severity scale — the SAME ladder as
// `contracts/findings.ts:FindingSeverity`, expressed as Zod so it is part of the
// answerer's structured-output schema. P0 = most severe, P3 = least.
export const AuditFindingSeverity = z.enum(["P0", "P1", "P2", "P3"]);
export type AuditFindingSeverity = z.infer<typeof AuditFindingSeverity>;

// One audit finding the model emits — the new first-class currency (mirrors
// `contracts/findings.ts:Finding`). `severity` is EXPLICIT, never inferred:
// the model declares P0–P3 directly. `id` is a stable slug so the same defect
// dedupes across re-audits; `fixHint` is the optional machine/agent hint the
// fix-in-place path (or a routed DAG spec) can act on.
export const AuditFinding = z
  .object({
    id: z.string().min(1).max(120),
    severity: AuditFindingSeverity,
    title: z.string().min(1).max(200),
    body: z.string().min(1).max(6000),
    // NULLISH (string | null | undefined): OpenAI's STRICT structured-output mode
    // (which `codex exec --output-schema` uses, via `enforceStrictNode`) requires
    // EVERY key in `required` and expresses optionality as a NULLABLE type — so the
    // generated schema sends `fixHint: null` for an omitted hint. The Zod source
    // (the runtime parser of the CLI response) MUST accept that `null`, else a valid
    // no-hint finding is rejected before the verdict can be recorded. Stored Findings
    // keep the frozen `{ fixHint?: string }` contract (contracts/findings.ts) — the
    // `null` is normalized to `undefined` on emit/read (see `normalizeFinding`).
    fixHint: z.string().min(1).max(2000).nullish(),
  })
  .strict();
export type AuditFinding = z.infer<typeof AuditFinding>;

/**
 * Normalize a parsed `AuditFinding` into the frozen stored `Finding` contract
 * (`contracts/findings.ts`): a `null` `fixHint` (the strict-schema "omitted" form)
 * collapses to an ABSENT key, so a finding emitted with `fixHint: null` and one
 * with `fixHint` omitted yield the BYTE-IDENTICAL stored shape `{ fixHint?: string }`.
 */
export function normalizeFinding(parsed: AuditFinding): {
  id: string;
  severity: AuditFindingSeverity;
  title: string;
  body: string;
  fixHint?: string;
} {
  return {
    id: parsed.id,
    severity: parsed.severity,
    title: parsed.title,
    body: parsed.body,
    // null (strict-schema "no hint") OR undefined (omitted) ⇒ absent key.
    ...(parsed.fixHint !== null && parsed.fixHint !== undefined && { fixHint: parsed.fixHint }),
  };
}

export const AuditAnswer = z
  .object({
    // The FINDINGS are the SOLE audit currency, and `findings` is REQUIRED — there is
    // NO `.default([])`. A genuinely audited-clean answer MUST emit an EXPLICIT
    // `findings: []`. An answer that OMITS findings FAILS TO PARSE — loudly — so no
    // `auditor.verdict` event is ever recorded for it, and the land-time no-event path
    // treats the run as UN-AUDITED → fail-closed P0. Clean `[]` is reachable ONLY from a
    // well-formed, explicitly-empty findings array.
    findings: z.array(AuditFinding),
  })
  .strict();

export type AuditAnswer = z.infer<typeof AuditAnswer>;
