// Auditor Answerer output schema. Source of truth for the JSON Schema used
// by `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/audit.json` and is regenerated by
// `scripts/answerer-schema-export.ts`.
//
// WAVE-2 / SLICE P-A (tanren-owns-the-engine.md §4): the auditor moves to
// FINDINGS-ONLY. The model now emits an explicit `findings: Finding[]` list with
// an EXPLICIT `severity: P0|P1|P2|P3` field — KILLING the inferred-severity
// derivation (§7) that today maps `passed`/`recommendedAction` → P0/P2/none in
// `contracts/dagLifecycle.ts`. The per-project `auditPosture` policy
// (`contracts/auditPosture.ts`) is the SOLE authority that turns these findings
// into a block/route/fix verdict.
//
// DE-RISK — DUAL-EMIT: this slice is ADDITIVE. The auditor emits BOTH the new
// `findings` AND the legacy verdict (`passed`/`reasoning`/`outstandingBehaviorIds`/
// `recommendedAction`) so nothing downstream breaks yet. A later slice (S1) reads
// findings; S3 deletes the legacy verdict. `findings` is OPTIONAL here so a
// legacy/fixture payload without it still parses during the transition.
import { z } from "zod";

export const AUDIT_ANSWER_SCHEMA_ID = "tanren.audit_answer.v2" as const;

export const AuditRecommendedAction = z.enum(["pass", "loop_to_planner", "halt"]);

// The explicit P0–P3 severity scale — the SAME ladder as
// `contracts/findings.ts:FindingSeverity`, expressed as Zod so it is part of the
// answerer's structured-output schema. P0 = most severe, P3 = least.
export const AuditFindingSeverity = z.enum(["P0", "P1", "P2", "P3"]);
export type AuditFindingSeverity = z.infer<typeof AuditFindingSeverity>;

// One audit finding the model emits — the new first-class currency (mirrors
// `contracts/findings.ts:Finding`). `severity` is EXPLICIT, never inferred:
// the model declares P0–P3 directly. `id` is a stable slug so the same defect
// dedupes across re-audits; `fixHint` is the optional machine/agent hint the
// fix-in-place path (or a routed DAG spec) can act on.
export const AuditFinding = z
  .object({
    id: z.string().min(1).max(120),
    severity: AuditFindingSeverity,
    title: z.string().min(1).max(200),
    body: z.string().min(1).max(6000),
    fixHint: z.string().min(1).max(2000).optional(),
  })
  .strict();
export type AuditFinding = z.infer<typeof AuditFinding>;

export const AuditAnswer = z
  .object({
    passed: z.boolean(),
    reasoning: z.string().min(1),
    outstandingBehaviorIds: z.array(z.string().min(1)),
    recommendedAction: AuditRecommendedAction,
    // WAVE-2 findings-only currency (dual-emitted alongside the legacy verdict).
    // Optional during the transition slice; the posture policy decides over it.
    findings: z.array(AuditFinding).default([]),
  })
  .strict();

export type AuditAnswer = z.infer<typeof AuditAnswer>;
export type AuditRecommendedAction = z.infer<typeof AuditRecommendedAction>;
