// Checker Answerer output schema. Source of truth for the JSON Schema used
// by `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/check.json` and is regenerated by
// `scripts/answerer-schema-export.ts`.
//
// SPEC-LOOP REDESIGN (docs/roadmap/spec-loop-redesign.md): the checker is
// COMPLETENESS-FINDINGS-ONLY. There is NO binary `passed`: the checker answers
// strictly "is THIS task complete for what DOWNSTREAM tasks depend on", and emits
// one finding per incompleteness. EVERY checker finding is P0 — nothing about
// delivering a task another task builds on is deferrable. An audited-complete task
// emits an EXPLICIT empty `findings: []` (so the deterministic loop reads "complete");
// ANY finding routes the task straight back to the writer.
//
// The checker NEVER judges high-level quality (that is the auditor) and NEVER runs
// or asserts tests/build/lint (a separate deterministic in-loop GATE owns
// correctness, and it runs BEFORE the checker). The field descriptions below carry
// that contract into the JSON Schema the model receives.
import { z } from "zod";

export const CHECK_ANSWER_SCHEMA_ID = "tanren.check_answer.v3" as const;

// One completeness finding: a concrete way THIS task is not yet complete for what
// downstream tasks build on. The stored severity is fixed P0 (the only severity the
// checker emits) so the finding is the SAME currency the auditor/triage reason over.
// `id` is a stable slug so the same gap dedupes across re-checks; `behaviorId` ties
// the gap to the subtask behavior it blocks (null when not behavior-scoped).
export const CheckFinding = z
  .object({
    id: z.string().min(1).max(120),
    title: z.string().min(1).max(200),
    body: z
      .string()
      .min(1)
      .max(6000)
      .describe("What downstream-relevant part of the task is missing/incomplete, with enough context to act on."),
    behaviorId: z.string().min(1).max(120).nullish(),
  })
  .strict();
export type CheckFinding = z.infer<typeof CheckFinding>;

export const CheckAnswer = z
  .object({
    // The completeness findings — the SOLE checker currency. REQUIRED, NO
    // `.default([])`: an audited-complete task emits an EXPLICIT empty list; an
    // answer that OMITS findings FAILS TO PARSE (loud). The deterministic loop
    // reads `findings.length === 0` as task-complete; ANY finding → back to writer.
    findings: z
      .array(CheckFinding)
      .describe(
        "Completeness findings (ALL treated as P0): one entry per way this task is not yet complete for what downstream tasks depend on. Empty array = complete.",
      ),
    reasoning: z
      .string()
      .min(1)
      .describe(
        "Per-criterion rationale: cite each acceptance criterion / behavior the downstream depends on and state whether the change delivers it. Do not assert or speculate about test/build/lint results (the gate owns those).",
      ),
  })
  .strict();

export type CheckAnswer = z.infer<typeof CheckAnswer>;
