// Checker Answerer output schema. Source of truth for the JSON Schema used
// by `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/check.json` and is regenerated by
// `scripts/answerer-schema-export.ts`.
//
// P3-0007: the checker judges INTENT satisfaction only — whether the diff
// fulfils the subtask intent and each explicit acceptance criterion. It must
// never run or assert tests/build/lint; a separate deterministic in-loop gate
// (P3-0005) owns correctness. The field descriptions below carry that
// contract into the JSON Schema the model receives.
import { z } from "zod";

export const CHECK_ANSWER_SCHEMA_ID = "tanren.check_answer.v2" as const;

export const CheckAnswer = z
  .object({
    passed: z
      .boolean()
      .describe(
        "Overall intent verdict: true only when the subtask intent and every relevant acceptance criterion are satisfied by the diff. Never reflects test/build/lint outcomes.",
      ),
    reasoning: z
      .string()
      .min(1)
      .describe(
        "Per-criterion rationale: cite each acceptance criterion / behavior and state whether the diff satisfies its intent. Do not assert or speculate about test/build/lint results.",
      ),
    behaviorIdsPassed: z.array(z.string().min(1)).describe("Behavior ids whose intent the diff satisfies."),
    behaviorIdsFailed: z.array(z.string().min(1)).describe("Behavior ids whose intent the diff does not satisfy."),
  })
  .strict();

export type CheckAnswer = z.infer<typeof CheckAnswer>;
