// Checker Answerer output schema. Source of truth for the JSON Schema used
// by `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/check.json` and is regenerated by
// `scripts/answerer-schema-export.ts`.
import { z } from "zod";

export const CHECK_ANSWER_SCHEMA_ID = "tanren.check_answer.v2" as const;

export const CheckAnswer = z
  .object({
    passed: z.boolean(),
    reasoning: z.string().min(1),
    behaviorIdsPassed: z.array(z.string().min(1)),
    behaviorIdsFailed: z.array(z.string().min(1))
  })
  .strict();

export type CheckAnswer = z.infer<typeof CheckAnswer>;
