// Conflict-resolution-planner Answerer output schema (PROJECT_BRIEF §2.2,
// §3.2; autonomy-engine.md §2b). Source of truth for the JSON Schema used by
// `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/conflict.json` and is regenerated by
// `scripts/answerer-schema-export.ts`.
//
// This is the DIFFERENTIATED Answerer: a conflict is a RE-PLANNING problem, not
// a text-picking problem. The resolver hands the model the conflict hunks, BOTH
// conflicting specs' intent + acceptance criteria, and the DAG edge between
// them, and the model returns ONE of two structured outcomes:
//
//   - `resolution`     — a resolution that preserves BOTH intents: the full
//                        resolved UTF-8 content for each conflicted file (the
//                        applied tree, never a fuzzy patch). The resolver writes
//                        these and RE-GATES (gate + checker + auditor) before any
//                        merge — an unverified resolution NEVER merges.
//   - `irreconcilable` — a structured diagnosis that the two intents cannot both
//                        be satisfied by a single edit. It names WHICH spec to
//                        route back to the planner and carries the OTHER spec's
//                        change as new planning context, so the intent stays
//                        ALIVE (re-planned), never silently dropped or merged.
//
// It is read-only like every Answerer: it never edits files, runs commands, or
// merges — it only reasons and returns the structured plan. The resolver (a
// Writer-adjacent applier over the runner) owns applying the tree + re-gating.
import { z } from "zod";

export const CONFLICT_ANSWER_SCHEMA_ID = "tanren.conflict_answer.v1" as const;

export const ConflictResolutionDecision = z
  .enum(["resolve", "irreconcilable"])
  .describe(
    "The resolution outcome: 'resolve' when a single tree satisfies BOTH specs' intent + acceptance criteria; 'irreconcilable' when no single edit can satisfy both and one spec must be re-planned with the other's change as context.",
  );

export const ResolvedFile = z
  .object({
    path: z
      .string()
      .min(1)
      .describe("The conflicted file path (repo-relative), exactly as presented in the conflict hunks."),
    content: z
      .string()
      .describe(
        "The FULL resolved UTF-8 content of the file with conflict markers removed, preserving BOTH specs' intent. This is the whole file, not a patch or a single hunk.",
      ),
  })
  .strict();

export const ConflictAnswer = z
  .object({
    decision: ConflictResolutionDecision,
    reasoning: z
      .string()
      .min(1)
      .describe(
        "Why this resolution preserves both intents (when 'resolve'), or why the two intents cannot both be satisfied by one edit (when 'irreconcilable'). Cite each conflicting spec's acceptance criteria.",
      ),
    // Present (and non-empty) ONLY when decision === 'resolve'. The validator
    // (decideConflictResolution) enforces the cross-field invariant so a model
    // that returns 'resolve' with no files — or 'irreconcilable' with files — is
    // rejected as non-conforming rather than silently mis-applied.
    resolvedFiles: z
      .array(ResolvedFile)
      .describe(
        "When decision='resolve': the full resolved content for EVERY conflicted file. Empty/omitted when decision='irreconcilable'.",
      )
      .default([]),
    // Present ONLY when decision === 'irreconcilable'. Names which of the two
    // specs to route back to the planner. The resolver maps this to a real spec
    // id from the two it presented and re-plans it with the other's change as
    // new context.
    replanSpec: ConflictReplanSpecSchema()
      .nullable()
      .default(null)
      .describe(
        "When decision='irreconcilable': which spec to re-plan ('merging' = the spec whose PR is merging; 'base' = the spec already on the base branch) plus the new planning context to carry. Null when decision='resolve'.",
      ),
  })
  .strict();

function ConflictReplanSpecSchema() {
  return z
    .object({
      which: z
        .enum(["merging", "base"])
        .describe(
          "Which spec re-plans: 'merging' (the spec whose PR is being merged) or 'base' (the spec already merged on the base branch).",
        ),
      newContext: z
        .string()
        .min(1)
        .describe(
          "The OTHER spec's change, summarized as new planning context so the re-planned spec satisfies its intent ON TOP of the other's change — keeping both intents alive.",
        ),
    })
    .strict();
}

export type ConflictResolutionDecision = z.infer<typeof ConflictResolutionDecision>;
export type ResolvedFile = z.infer<typeof ResolvedFile>;
export type ConflictAnswer = z.infer<typeof ConflictAnswer>;
