// Convergence Answerer output schema. Source of truth for the JSON Schema used by
// `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/convergence.json` and is regenerated by `scripts/answerer-schema-export.ts`.
//
// SPEC-LOOP REDESIGN (docs/roadmap/spec-loop-redesign.md): the CONVERGENCE answerer
// runs on the loopback when work was kept IN-SPEC (triage routed at least one `task`).
// It decides PROGRESS vs STALL from the finding-DELTA across loops + the diff. It is
// the SOLE loop bound — there is NO retry cap / per-spec rerun limit / timeout halt.
//
// The agent's `assessment` is its read; the deterministic loop applies the
// CONFIGURABLE convergence policy (read from `auditPosture`/project config):
//   (a) total P-score decreasing,
//   (b) root-causes not recurring,
//   (c) velocity middle-ground (mild leftovers after several rounds → defer as specs,
//       allow → PASS).
// PROGRESS → continue the loop. STALL → increment a CONSECUTIVE-stall counter; after N
// consecutive stalls the run HALTS `convergence_stalled` (a human action: rework the
// spec / stronger model / fix the environment).
import { z } from "zod";

export const CONVERGENCE_ANSWER_SCHEMA_ID = "tanren.convergence_answer.v1" as const;

// The agent's read of the loop's trajectory:
//   - `progress`        — the finding-delta is shrinking / root causes are being
//                         retired; keep iterating.
//   - `stalled`         — the same root causes recur with no forward progress; a
//                         human action is the genuine next step.
//   - `velocity_defer`  — only MILD leftovers remain (e.g. P3-only after several
//                         rounds); under a velocity posture, defer them as specs and
//                         allow the spec to PASS rather than loop further.
export const ConvergenceAssessment = z.enum(["progress", "stalled", "velocity_defer"]);
export type ConvergenceAssessment = z.infer<typeof ConvergenceAssessment>;

export const ConvergenceAnswer = z
  .object({
    assessment: ConvergenceAssessment,
    // The agent's evidence: cite the finding-delta (which root causes were retired,
    // which recurred) and the change since the prior loop. REQUIRED + non-empty so a
    // stall/defer decision is always justified in the timeline.
    reasoning: z
      .string()
      .min(1)
      .describe(
        "Cite the finding-delta across loops: which root causes were retired, which recurred, and whether the total P-score is decreasing.",
      ),
  })
  .strict();

export type ConvergenceAnswer = z.infer<typeof ConvergenceAnswer>;
