// Demo Answerer output schema. Source of truth for the JSON Schema used by
// the spec-completion narration generator. The generated JSON
// Schema lives at `generated/demo.json` and is regenerated by
// `scripts/answerer-schema-export.ts`.
import { z } from "zod";

export const DEMO_ANSWER_SCHEMA_ID = "tanren.demo_answer.v1" as const;

export const DemoLink = z
  .object({
    label: z.string().min(1),
    url: z.string().url(),
  })
  .strict();

export const DemoAnswer = z
  .object({
    headline: z.string().min(1),
    body: z.string().min(1),
    highlightBehaviorIds: z.array(z.string().min(1)),
    showStopperRisks: z.array(z.string().min(1)).default([]),
    links: z.array(DemoLink).default([]),
  })
  .strict();

export type DemoAnswer = z.infer<typeof DemoAnswer>;
export type DemoLink = z.infer<typeof DemoLink>;
