// Demo-Run Answerer output schema. Source of truth for the JSON Schema used by
// `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/demoRun.json` and is regenerated by `scripts/answerer-schema-export.ts`.
//
// SPEC-LOOP REDESIGN (docs/roadmap/spec-loop-redesign.md): the DEMO-RUN answerer is
// the "does the thing the spec was written for actually WORK" gate, run AFTER the
// auditor and gating the spec's pass. It is DISTINCT from:
//   - the checker (per-task completeness for downstream tasks), and
//   - the auditor (quality/security/perf/scalability).
// It exercises the real user-flow / e2e behavior the spec promised. It is an
// OPTIONAL/FLAGGED slot (a project/spec config can disable it — it is hard for some
// project types) but the slot is wired so a project that enables it gets a real
// "show me it works" gate.
//
// FINDINGS-ONLY, like the auditor: the agent emits `findings: Finding[]` (each with an
// EXPLICIT severity P0–P3) describing what did NOT work, and renders NO verdict. A
// working demo emits an EXPLICIT empty `findings: []`. The findings flow into the SAME
// triage/convergence routing the auditor's do (the spec-gate CI-as-P0 + auditor + demo
// findings are triaged together).
import { z } from "zod";

import { AuditFinding } from "./audit.js";

export const DEMO_RUN_ANSWER_SCHEMA_ID = "tanren.demo_run_answer.v1" as const;

// The demo-run finding shares the auditor `AuditFinding` shape (explicit P0–P3
// severity + stable id + optional fixHint) so the triage stage reasons over ONE
// finding currency regardless of which stage emitted it.
export const DemoRunFinding = AuditFinding;
export type DemoRunFinding = z.infer<typeof DemoRunFinding>;

export const DemoRunAnswer = z
  .object({
    // The demo findings — REQUIRED, NO `.default([])`. A demo that exercised the
    // promised behavior successfully emits an EXPLICIT empty list; an answer that
    // OMITS findings FAILS TO PARSE (loud). Each finding describes a way the real
    // user-flow did not work, with an explicit severity.
    findings: z
      .array(DemoRunFinding)
      .describe("Demo findings (explicit P0–P3): one per way the promised user-flow did not work. Empty = it works."),
    // A short human-facing narration of WHAT was exercised (the steps the agent ran
    // to demonstrate the spec's promise). REQUIRED + non-empty so the timeline records
    // what the demo actually did, even on a clean pass.
    summary: z.string().min(1).describe("What user-flow/e2e steps were exercised to demonstrate the spec's promise."),
  })
  .strict();

export type DemoRunAnswer = z.infer<typeof DemoRunAnswer>;
