// Design-Oracle Answerer output schema. Source of truth for the JSON Schema used by
// `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/designOracle.json` and is regenerated by `scripts/answerer-schema-export.ts`.
//
// NATIVE DESIGN SUBSYSTEM (WS-D4 of docs/roadmap/native-design-subsystem.md): the
// DESIGN ORACLE is the domain-aware design/visual VERIFICATION answerer. It judges
// whether the built output satisfies the project's first-class `DesignContract`
// (WS-D1) — replacing today's situation where there is NO design verification (the
// static demo cannot assess design). It is DISTINCT from:
//   - the checker (per-task completeness for downstream tasks),
//   - the auditor (quality/security/perf/scalability), and
//   - the demo-run answerer (does the promised user-flow work).
// The design oracle answers strictly "does the built output match the DESIGN
// CONTRACT" — behavior-coverage of designed surfaces + persona-scoped fidelity +
// the contract's domain-adaptive dimensions.
//
// THE MOAT (what no standalone design tool CAN do — it exploits Tanren's native
// entity graph): the oracle verifies against TYPED entities, not guesses.
//   - BEHAVIOR COVERAGE: every `behaviorRef` the contract is responsible for must
//     have a corresponding designed/implemented surface or flow. A behavior with no
//     covering surface is a coverage GAP (a finding). This is an exhaustive checklist
//     derived from first-class behaviors — a handoff design tool has no behavior model.
//   - PERSONA-SCOPED FIDELITY: each persona's surfaces are verified against the
//     contract's persona-scoped dimensions. No "assume default admin" guessing —
//     personas are RESOLVED (the contract binds to the persona graph, WS-D1).
//   - DOMAIN-AWARE MODE: HOW it verifies is DERIVED from the contract's domain +
//     dimensions (web UI → render/inspect surfaces; a non-web domain → inspect the
//     relevant artifacts — prose/typography for a novel, art/feel for a game).
//     NEVER web-baked: the oracle is told the domain + the dimensions' intents and
//     decides the verification mode, mirroring how the oracle taxonomy / lifecycle
//     stay domain-general. Tanren NEVER branches on the domain in code.
//
// FINDINGS-ONLY, like the auditor + demo-run: the agent emits `findings: Finding[]`,
// each with an EXPLICIT severity P0–P3, and renders NO verdict. A design-faithful
// output emits an EXPLICIT empty `findings: []`. The findings flow into the SAME
// triage/convergence routing as the auditor's + demo's (one finding currency), so a
// genuine fidelity gap RE-DRIVES the writer exactly like any other gate finding.
import { z } from "zod";

import { AuditFinding } from "./audit.js";

export const DESIGN_ORACLE_ANSWER_SCHEMA_ID = "tanren.design_oracle_answer.v1" as const;

// A design fidelity finding shares the auditor `AuditFinding` shape (explicit P0–P3
// severity + stable id + optional fixHint) so the triage stage reasons over ONE
// finding currency regardless of which stage emitted it. A behavior-coverage gap, a
// persona-scoped fidelity miss, and a dimension violation are all expressed as
// findings here (the `body` names which behavior/persona/dimension it concerns).
export const DesignOracleFinding = AuditFinding;
export type DesignOracleFinding = z.infer<typeof DesignOracleFinding>;

export const DesignOracleAnswer = z
  .object({
    // The verification MODE the oracle actually used, DERIVED from the contract's
    // domain + dimensions (e.g. "web-render", "static-surface-inspection",
    // "prose-typography", "art-direction-review"). REQUIRED + non-empty so the
    // timeline records HOW design was verified for this domain — the domain-aware
    // posture is observable, never assumed web. The agent chooses it from the domain;
    // Tanren never dictates an enum (domain-general, like the dimension keys).
    verificationMode: z
      .string()
      .min(1)
      .max(200)
      .describe(
        "The domain-derived verification mode the oracle used (e.g. web-render, prose-typography, art-direction-review). Chosen from the contract's domain + dimensions, never a Tanren-fixed enum.",
      ),
    // The design fidelity findings — the SOLE oracle currency. REQUIRED, NO
    // `.default([])`: a design-faithful output emits an EXPLICIT empty list; an answer
    // that OMITS findings FAILS TO PARSE (loud). Each finding is a way the built output
    // does NOT satisfy the contract: an uncovered behavior (coverage gap), a
    // persona-scoped surface that is wrong for its resolved persona, or a violated
    // contract dimension. The findings route through the SAME triage as auditor/demo.
    findings: z
      .array(DesignOracleFinding)
      .describe(
        "Design fidelity findings (explicit P0–P3): one per behavior-coverage gap, persona-scoped fidelity miss, or violated contract dimension. Empty = the output is design-faithful.",
      ),
    // A short human-facing narration of WHAT was inspected against the contract (the
    // surfaces/artifacts read + which behaviors/personas/dimensions were checked).
    // REQUIRED + non-empty so the timeline records what design verification actually
    // did, even on a clean pass.
    summary: z
      .string()
      .min(1)
      .describe(
        "What the oracle inspected against the contract: the surfaces/artifacts read and which behaviors/personas/dimensions were verified.",
      ),
  })
  .strict();

export type DesignOracleAnswer = z.infer<typeof DesignOracleAnswer>;
