// Forge Answerer (conversation-turn) output schema. Source of truth for the
// JSON Schema used by the Forge narration generator. Forge writes
// one turn at a time; this schema describes a single turn including the
// typed tool-call surface that will consume when wiring real tool
// stubs. The generated JSON Schema lives at `generated/forge.json` and is
// regenerated by `scripts/answerer-schema-export.ts`.
import { z } from "zod";

export const FORGE_ANSWER_SCHEMA_ID = "tanren.forge_answer.v1" as const;

export const ForgeToolCall = z.discriminatedUnion("tool", [
  z
    .object({
      tool: z.literal("tanren.read_spec"),
      args: z.object({ specId: z.string().min(1) }).strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.read_run"),
      args: z.object({ runId: z.string().min(1) }).strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.read_events"),
      args: z
        .object({
          runId: z.string().min(1).nullish(),
          specId: z.string().min(1).nullish(),
          since: z.string().min(1).nullish(),
          limit: z.number().int().nullish(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.read_costs"),
      args: z
        .object({
          runId: z.string().min(1).nullish(),
          since: z.string().min(1).nullish(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.read_behaviors"),
      args: z.object({ projectId: z.string().min(1) }).strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.read_milestones"),
      args: z.object({ projectId: z.string().min(1) }).strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.read_insights"),
      args: z.object({ projectId: z.string().min(1) }).strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("repo.read_file"),
      args: z
        .object({
          projectId: z.string().min(1),
          path: z.string().min(1),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("repo.grep"),
      args: z
        .object({
          projectId: z.string().min(1),
          pattern: z.string().min(1),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("repo.read_issue"),
      args: z
        .object({
          projectId: z.string().min(1),
          number: z.number().int(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.create_spec"),
      args: z
        .object({
          projectId: z.string().min(1),
          title: z.string().min(1),
          description: z.string().min(1),
          behaviorIds: z.array(z.string().min(1)).nullish(),
          milestoneId: z.string().min(1).nullish(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.trigger_run"),
      args: z.object({ specId: z.string().min(1) }).strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.rerun_task"),
      args: z.object({ taskId: z.string().min(1) }).strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.acknowledge_insight"),
      args: z.object({ insightId: z.string().min(1) }).strict(),
    })
    .strict(),
]);

export const ForgeSuggestedAction = z
  .object({
    label: z.string().min(1),
    toolCall: ForgeToolCall,
  })
  .strict();

// follow-up (write-action approval): the four write tools the answerer
// may PROPOSE on a final answer. The model never executes these — the engine
// persists each as a pending proposal that a human approves before the write
// runs under the approving operator's authz. Mirrors the write family already
// in `engine/forge/tools/write.ts`.
export const ForgeWriteToolCall = z.discriminatedUnion("tool", [
  z
    .object({
      tool: z.literal("tanren.create_spec"),
      args: z
        .object({
          projectId: z.string().min(1),
          title: z.string().min(1),
          description: z.string().min(1),
          behaviorIds: z.array(z.string().min(1)).nullish(),
          milestoneId: z.string().min(1).nullish(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.trigger_run"),
      args: z.object({ specId: z.string().min(1) }).strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.rerun_task"),
      args: z.object({ taskId: z.string().min(1) }).strict(),
    })
    .strict(),
  z
    .object({
      tool: z.literal("tanren.acknowledge_insight"),
      args: z.object({ insightId: z.string().min(1) }).strict(),
    })
    .strict(),
]);

// A proposed write the answerer wants a human to approve. Carried on the final
// ForgeAnswer; the engine persists it pending and never executes it directly.
export const ForgeProposedAction = z
  .object({
    toolCall: ForgeWriteToolCall,
    // A short, human-readable justification the reviewer sees before approving.
    rationale: z.string().min(1).max(1000),
  })
  .strict();

export const ForgeAttentionPriority = z.enum(["review", "decide", "budget", "blocked", "info"]);

export const ForgeAttentionItem = z
  .object({
    priority: ForgeAttentionPriority,
    title: z.string().min(1),
    sub: z.string(),
    action: ForgeSuggestedAction.nullable(),
  })
  .strict();

export const ForgeInsightKind = z.enum(["retry_hotspot", "model_mismatch", "pace_anomaly", "stuck", "review_stall"]);

export const ForgeInsight = z
  .object({
    kind: ForgeInsightKind,
    title: z.string().min(1),
    body: z.string().min(1),
    actions: z.array(ForgeSuggestedAction),
  })
  .strict();

export const ForgeAnswer = z
  .object({
    body: z.string().min(1),
    attentionItems: z.array(ForgeAttentionItem).default([]),
    insights: z.array(ForgeInsight).default([]),
    prompts: z.array(z.string().min(1)).default([]),
    // Write actions the answerer PROPOSES this turn. The conversation engine
    // persists each as a pending `forge_action_proposals` row and never
    // executes it — a human approves it through the approve endpoint, which
    // runs the write under the approving operator's authz. Optional so the
    // common (read-only) answer omits it; absent === no proposals.
    proposedActions: z.array(ForgeProposedAction).nullish(),
  })
  .strict();

export type ForgeAnswer = z.infer<typeof ForgeAnswer>;
export type ForgeToolCall = z.infer<typeof ForgeToolCall>;
export type ForgeWriteToolCall = z.infer<typeof ForgeWriteToolCall>;
export type ForgeProposedAction = z.infer<typeof ForgeProposedAction>;
export type ForgeSuggestedAction = z.infer<typeof ForgeSuggestedAction>;
export type ForgeAttentionItem = z.infer<typeof ForgeAttentionItem>;
export type ForgeInsight = z.infer<typeof ForgeInsight>;
export type ForgeAttentionPriority = z.infer<typeof ForgeAttentionPriority>;
export type ForgeInsightKind = z.infer<typeof ForgeInsightKind>;
