// Single import surface for the five Phase 2 Answerer schemas (plan, check,
// audit, demo, forge). The Zod schemas in this directory are the single
// source of truth; the committed JSON Schema files under `generated/` are
// regenerated by `scripts/answerer-schema-export.ts` and consumed by
// `codex exec --output-schema` callers.
import { z, type ZodType } from "zod";

import { AUDIT_ANSWER_SCHEMA_ID, AuditAnswer } from "./audit.js";
import { CHECK_ANSWER_SCHEMA_ID, CheckAnswer } from "./check.js";
import { DEMO_ANSWER_SCHEMA_ID, DemoAnswer } from "./demo.js";
import { FORGE_ANSWER_SCHEMA_ID, ForgeAnswer } from "./forge.js";
import { PLAN_ANSWER_SCHEMA_ID, PlanAnswer } from "./plan.js";

export {
  PlanAnswer,
  PlanSubtask,
  PLAN_ANSWER_SCHEMA_ID
} from "./plan.js";
export {
  CheckAnswer,
  CHECK_ANSWER_SCHEMA_ID
} from "./check.js";
export {
  AuditAnswer,
  AuditRecommendedAction,
  AUDIT_ANSWER_SCHEMA_ID
} from "./audit.js";
export {
  DemoAnswer,
  DemoLink,
  DEMO_ANSWER_SCHEMA_ID
} from "./demo.js";
export {
  ForgeAnswer,
  ForgeToolCall,
  ForgeSuggestedAction,
  ForgeAttentionItem,
  ForgeInsight,
  ForgeAttentionPriority,
  ForgeInsightKind,
  FORGE_ANSWER_SCHEMA_ID
} from "./forge.js";
export { answererOutputSchemaFor, type AnswererOutputSchema } from "./adapter.js";

export type AnswererRole = "plan" | "check" | "audit" | "demo" | "forge";

export interface AnswererSchemaDescriptor {
  readonly role: AnswererRole;
  readonly schemaId: string;
  readonly generatedFile: string;
  readonly zod: ZodType;
}

// answererSchemaCatalog drives both the codegen step
// (scripts/answerer-schema-export.ts) and the drift test
// (services/orchestrator/tests/answererSchemaDrift.test.ts). Order is part
// of the contract: keeping it stable keeps the generated file ordering
// stable for human-friendly diffs.
export const answererSchemaCatalog: Readonly<Record<AnswererRole, AnswererSchemaDescriptor>> = {
  plan: {
    role: "plan",
    schemaId: PLAN_ANSWER_SCHEMA_ID,
    generatedFile: "plan.json",
    zod: PlanAnswer
  },
  check: {
    role: "check",
    schemaId: CHECK_ANSWER_SCHEMA_ID,
    generatedFile: "check.json",
    zod: CheckAnswer
  },
  audit: {
    role: "audit",
    schemaId: AUDIT_ANSWER_SCHEMA_ID,
    generatedFile: "audit.json",
    zod: AuditAnswer
  },
  demo: {
    role: "demo",
    schemaId: DEMO_ANSWER_SCHEMA_ID,
    generatedFile: "demo.json",
    zod: DemoAnswer
  },
  forge: {
    role: "forge",
    schemaId: FORGE_ANSWER_SCHEMA_ID,
    generatedFile: "forge.json",
    zod: ForgeAnswer
  }
} as const;

export function listAnswererSchemas(): ReadonlyArray<AnswererSchemaDescriptor> {
  return (Object.keys(answererSchemaCatalog) as AnswererRole[]).map((role) => answererSchemaCatalog[role]);
}

// renderAnswererJsonSchema is the single chokepoint that converts a Zod
// source schema to the JSON Schema shape used both by `codex exec
// --output-schema` and by the codegen script. Keeping this here means the
// codegen and the drift test never need to know what `zod-to-json-schema`
// arguments to pass.
export function renderAnswererJsonSchema(zodSchema: ZodType): Record<string, unknown> {
  return z.toJSONSchema(zodSchema, { target: "draft-2020-12" }) as Record<string, unknown>;
}
