// Single import surface for the Answerer schemas (plan, check, audit, demo,
// forge, review). The Zod schemas in this directory are the single
// source of truth; the committed JSON Schema files under `generated/` are
// regenerated by `scripts/answerer-schema-export.ts` and consumed by
// `codex exec --output-schema` callers.
import { z, type ZodType } from "zod";

import { answererSchemaCatalog, type AnswererRole, type AnswererSchemaDescriptor } from "./catalog.js";

export { PlanAnswer, PlanSubtask, PLAN_ANSWER_SCHEMA_ID } from "./plan.js";
export { CheckAnswer, CHECK_ANSWER_SCHEMA_ID } from "./check.js";
export { AuditAnswer, AuditRecommendedAction, AUDIT_ANSWER_SCHEMA_ID } from "./audit.js";
export { DemoAnswer, DemoLink, DEMO_ANSWER_SCHEMA_ID } from "./demo.js";
export {
  ForgeAnswer,
  ForgeToolCall,
  ForgeWriteToolCall,
  ForgeProposedAction,
  ForgeSuggestedAction,
  ForgeAttentionItem,
  ForgeInsight,
  ForgeAttentionPriority,
  ForgeInsightKind,
  FORGE_ANSWER_SCHEMA_ID,
} from "./forge.js";
export { ReviewAnswer, ReviewVerdictDecision, REVIEW_ANSWER_SCHEMA_ID } from "./review.js";
export { answererOutputSchemaFor, type AnswererOutputSchema } from "./adapter.js";

export { answererSchemaCatalog, type AnswererRole, type AnswererSchemaDescriptor } from "./catalog.js";

export function listAnswererSchemas(): ReadonlyArray<AnswererSchemaDescriptor> {
  return (Object.keys(answererSchemaCatalog) as AnswererRole[]).map((role) => answererSchemaCatalog[role]);
}

// renderAnswererJsonSchema is the single chokepoint that converts a Zod
// source schema to the JSON Schema shape used both by `codex exec
// --output-schema` and by the codegen script. Keeping this here means the
// codegen and the drift test never need to know what `zod-to-json-schema`
// arguments to pass.
export function renderAnswererJsonSchema(zodSchema: ZodType): Record<string, unknown> {
  return z.toJSONSchema(zodSchema, { target: "draft-2020-12" }) as Record<string, unknown>;
}
