// Planner Answerer output schema. Source of truth for the JSON Schema used
// by `codex exec --output-schema` and consumed by P2A-0012 (planner feedback
// loops). The generated JSON Schema lives next to this file under
// `generated/plan.json` and is regenerated by
// `scripts/answerer-schema-export.ts`.
import { z } from "zod";

export const PLAN_ANSWER_SCHEMA_ID = "tanren.plan_answer.v1" as const;

export const PlanSubtask = z
  .object({
    index: z.number().int(),
    title: z.string().min(1),
    intent: z.string().min(1),
    behaviorIds: z.array(z.string().min(1)),
    estimatedTokens: z.number().int().nullable()
  })
  .strict();

export const PlanAnswer = z
  .object({
    subtasks: z.array(PlanSubtask).min(1),
    rationale: z.string().min(1)
  })
  .strict();

export type PlanSubtask = z.infer<typeof PlanSubtask>;
export type PlanAnswer = z.infer<typeof PlanAnswer>;
