// Reviewer Answerer output schema. Source of truth for the JSON Schema used by
// `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/review.json` and is regenerated by
// `scripts/answerer-schema-export.ts`.
//
// The simulated reviewer is the orchestrator-managed stand-in for a human PR
// reviewer (reviewPolicy: "simulated"). It reads the PR diff + the spec's
// title/description/acceptance-criteria and returns a single verdict, which the
// review stage then posts as a REAL GitHub review on the PR. It is read-only
// an Answerer: it never edits files, runs commands, or merges — it only
// judges and explains.
import { z } from "zod";

export const REVIEW_ANSWER_SCHEMA_ID = "tanren.review_answer.v1" as const;

export const ReviewVerdictDecision = z
  .enum(["approve", "request_changes"])
  .describe(
    "The review verdict: 'approve' when the PR diff fulfils the spec intent and every acceptance criterion; 'request_changes' when any criterion is unmet or the diff is incorrect/incomplete.",
  );

export const ReviewAnswer = z
  .object({
    verdict: ReviewVerdictDecision,
    reasoning: z
      .string()
      .min(1)
      .describe(
        "Reviewer rationale posted as the GitHub review body: cite each acceptance criterion and state whether the diff satisfies it, and call out any blocking concerns when requesting changes.",
      ),
  })
  .strict();

export type ReviewAnswer = z.infer<typeof ReviewAnswer>;
export type ReviewVerdictDecision = z.infer<typeof ReviewVerdictDecision>;
