// Triage Answerer output schema. Source of truth for the JSON Schema used by
// `codex exec --output-schema`. The generated JSON Schema lives at
// `generated/triage.json` and is regenerated by `scripts/answerer-schema-export.ts`.
//
// SPEC-LOOP REDESIGN (docs/roadmap/spec-loop-redesign.md): the TRIAGE answerer
// takes ALL findings (spec-gate CI-as-P0 + auditor + demo) and produces M WORK
// ITEMS deduped to ROOT CAUSES (not 1:1 with findings). Each item is tagged
// `kind: task | spec` and carries an explicit `severity P0–P3`:
//   - `task` → appended to THIS spec's task list (re-enter the writer loop),
//   - `spec` → emitted as a NEW DAG spec (through the spec-creating contract).
// The deterministic loop applies the routing policy (P0 → tasks-here by default;
// P1–P3 → tasks-here OR new specs by `auditPosture`/config). If triage routes ALL
// findings to new specs (no `task` items kept) → the spec PASSES (the triage→passed
// arrow). The agent renders NO pass/fail verdict — it only dedupes + classifies.
import { z } from "zod";

export const TRIAGE_ANSWER_SCHEMA_ID = "tanren.triage_answer.v1" as const;

export const TriageSeverity = z.enum(["P0", "P1", "P2", "P3"]);
export type TriageSeverity = z.infer<typeof TriageSeverity>;

// A work item's natural HOME, declared by the agent as a HINT (the deterministic
// routing policy in the loop is the final authority, by severity + auditPosture):
//   - `task` — a bounded fix that belongs in THIS spec's task list.
//   - `spec` — a coherent, demo-able unit big enough to be its own DAG spec.
export const TriageItemKind = z.enum(["task", "spec"]);
export type TriageItemKind = z.infer<typeof TriageItemKind>;

// One triaged work item — a ROOT CAUSE that may subsume several raw findings.
// `findingIds` records which input findings this item resolves (the dedup trail);
// `title`/`body` are the actionable description a writer (task) or the spec-creating
// contract (spec) consumes; `severity` is the worst severity among the subsumed
// findings; `kind` is the agent's home hint.
export const TriageWorkItem = z
  .object({
    id: z.string().min(1).max(120),
    kind: TriageItemKind,
    severity: TriageSeverity,
    title: z.string().min(1).max(200),
    body: z.string().min(1).max(6000),
    findingIds: z
      .array(z.string().min(1))
      .describe("The ids of the input findings this root-cause item subsumes (the dedup trail)."),
  })
  .strict();
export type TriageWorkItem = z.infer<typeof TriageWorkItem>;

export const TriageAnswer = z
  .object({
    // The deduped work items — REQUIRED, NO `.default([])`. An empty list is a valid,
    // explicit "no actionable root causes" answer (rare, but legal); an OMITTED list
    // FAILS TO PARSE (loud). The loop routes each item by kind + severity + posture.
    workItems: z
      .array(TriageWorkItem)
      .describe("M work items deduped to root causes (NOT 1:1 with findings), each tagged task|spec + severity."),
  })
  .strict();

export type TriageAnswer = z.infer<typeof TriageAnswer>;
