import {
  AuditPostureStrandsFindingsPayload,
  AuditorCompletedPayload,
  AuditorFailedPayload,
  AuditorFindingsRoutedPayload,
  AuditorRejectedPayload,
  AuditorStartedPayload,
  AuditorVerdictPayload,
  CheckerCompletedPayload,
  CheckerFailedPayload,
  CheckerRejectedPayload,
  CheckerStartedPayload,
  CheckerVerdictPayload,
  loopEventRegistry,
  PlannerCompletedPayload,
  PlannerFailedPayload,
  PlannerRerequestedPayload,
  PlannerStartedPayload,
  PlannerSubtasksEmittedPayload,
  templateEventRegistry,
  WriterCompletedPayload,
  WriterFailedPayload,
  WriterStartedPayload,
  WriterSubtaskCompletedPayload,
  WriterSubtaskFailedPayload,
  WriterSubtaskProgressPayload,
  WriterSubtaskStartedPayload,
} from "./answerer.js";

export const agentEventRegistry = {
  "planner.started": PlannerStartedPayload,
  "planner.completed": PlannerCompletedPayload,
  "planner.failed": PlannerFailedPayload,
  "planner.subtasks.emitted": PlannerSubtasksEmittedPayload,
  "planner.rerequested": PlannerRerequestedPayload,
  "writer.started": WriterStartedPayload,
  "writer.completed": WriterCompletedPayload,
  "writer.failed": WriterFailedPayload,
  "writer.subtask.started": WriterSubtaskStartedPayload,
  "writer.subtask.completed": WriterSubtaskCompletedPayload,
  "writer.subtask.failed": WriterSubtaskFailedPayload,
  "writer.subtask.progress": WriterSubtaskProgressPayload,
  "checker.started": CheckerStartedPayload,
  "checker.completed": CheckerCompletedPayload,
  "checker.failed": CheckerFailedPayload,
  "checker.verdict": CheckerVerdictPayload,
  "checker.rejected": CheckerRejectedPayload,
  "auditor.started": AuditorStartedPayload,
  "auditor.completed": AuditorCompletedPayload,
  "auditor.failed": AuditorFailedPayload,
  "auditor.verdict": AuditorVerdictPayload,
  "auditor.rejected": AuditorRejectedPayload,
  "auditor.findings_routed": AuditorFindingsRoutedPayload,
  "audit.posture_strands_findings": AuditPostureStrandsFindingsPayload,
  ...loopEventRegistry,
  ...templateEventRegistry,
} as const;
