import {
  DagBudgetMilestonePayload,
  DagBudgetPausedPayload,
  DagConcurrencySaturatedPayload,
  DagConfigCorruptPayload,
  DagDrainedPayload,
  DagSpecAncestorNotReadyPayload,
  DagSpecAttentionResolvedPayload,
  DagSpecEnqueuedPayload,
  DagSpecNeedsAttentionPayload,
  DagSpecPercolatedPayload,
  DagSpecPercolatingPayload,
  DagSpecPercolationDeferredPayload,
  DagSpecPercolationReplanPayload,
  DagSpecRedrivenPayload,
  DagSpecSpeculationHeldPayload,
  DagSpecSpeculativePayload,
  IntegrationProofReusedPayload,
  IntegrationRebasePayload,
} from "./dag.js";

export const dagEventRegistry = {
  "dag.spec.enqueued": DagSpecEnqueuedPayload,
  "dag.drained": DagDrainedPayload,
  "dag.budget.paused": DagBudgetPausedPayload,
  "dag.budget.milestone": DagBudgetMilestonePayload,
  "dag.concurrency.saturated": DagConcurrencySaturatedPayload,
  "dag.config.corrupt": DagConfigCorruptPayload,
  "dag.spec.speculative": DagSpecSpeculativePayload,
  "dag.spec.speculation_held": DagSpecSpeculationHeldPayload,
  "dag.spec.ancestor_not_ready": DagSpecAncestorNotReadyPayload,
  "dag.spec.redriven": DagSpecRedrivenPayload,
  "dag.spec.percolating": DagSpecPercolatingPayload,
  "dag.spec.percolated": DagSpecPercolatedPayload,
  "dag.spec.percolation_deferred": DagSpecPercolationDeferredPayload,
  "dag.spec.percolation_replan": DagSpecPercolationReplanPayload,
  "integration.rebase": IntegrationRebasePayload,
  "integration.proof.reused": IntegrationProofReusedPayload,
  "dag.spec.needs_attention": DagSpecNeedsAttentionPayload,
  "dag.spec.attention_resolved": DagSpecAttentionResolvedPayload,
} as const;
