import {
  MergeBehindPayload,
  MergeBlockedPayload,
  MergeCompletedPayload,
  MergeConflictEntityMergedPayload,
  MergeConflictIrreconcilablePayload,
  MergeConflictPayload,
  MergeConflictReplanRoutedPayload,
  MergeConflictResolvedPayload,
  MergeConflictResolvingPayload,
  MergeFailedPayload,
  MergeQueuedPayload,
  MergeRebasedPayload,
  MergeRegatePendingPayload,
  MergeRetargetedPayload,
  MergeSpeculativeHeldPayload,
  ReviewApprovedPayload,
  ReviewAutoApprovedPayload,
  ReviewChangesRequestedPayload,
  ReviewRequestedPayload,
} from "./integrations.js";
import { MergeScheduledPayload } from "./mergeQueue.js";

export const reviewAndMergeEventRegistry = {
  "review.requested": ReviewRequestedPayload,
  "review.approved": ReviewApprovedPayload,
  "review.auto_approved": ReviewAutoApprovedPayload,
  "review.changes_requested": ReviewChangesRequestedPayload,
  "merge.scheduled": MergeScheduledPayload,
  "merge.queued": MergeQueuedPayload,
  "merge.completed": MergeCompletedPayload,
  "merge.failed": MergeFailedPayload,
  "merge.conflict": MergeConflictPayload,
  "merge.behind": MergeBehindPayload,
  "merge.rebased": MergeRebasedPayload,
  "merge.regate_pending": MergeRegatePendingPayload,
  "merge.conflict.resolving": MergeConflictResolvingPayload,
  "merge.conflict.resolved": MergeConflictResolvedPayload,
  "merge.conflict.entity_merged": MergeConflictEntityMergedPayload,
  "merge.conflict.irreconcilable": MergeConflictIrreconcilablePayload,
  "merge.conflict.replan_routed": MergeConflictReplanRoutedPayload,
  "merge.blocked": MergeBlockedPayload,
  "merge.speculative_held": MergeSpeculativeHeldPayload,
  "merge.retargeted": MergeRetargetedPayload,
} as const;
