// GENERATED FILE — do not edit by hand.
// Regenerate via `corepack pnpm run codegen:events` (or `node scripts/generate-event-type-check.mjs`).
// Source of truth: services/orchestrator/src/engine/events/registry.ts (Zod EventRegistry).

export const eventTypeNames = [
  "allocator.allocated",
  "allocator.failed",
  "allocator.requested",
  "auditor.completed",
  "auditor.failed",
  "auditor.started",
  "auditor.verdict",
  "checker.completed",
  "checker.failed",
  "checker.started",
  "checker.verdict",
  "ci.failed",
  "ci.passed",
  "ci.started",
  "cost.failed",
  "cost.resolved",
  "credential.failed",
  "credential.loaded",
  "credential.requested",
  "github.branch.pushed",
  "github.failed",
  "github.pr.created",
  "github.pr.merged",
  "github.pr.ready",
  "hello.completed",
  "hello.ssh_completed",
  "hello.ssh_started",
  "hello.started",
  "notification.enqueued",
  "notification.failed",
  "notification.sent",
  "phase1.fixture.ci_pending",
  "phase1.fixture.completed",
  "phase1.fixture.failed",
  "phase1.fixture.started",
  "planner.completed",
  "planner.failed",
  "planner.started",
  "planner.subtasks.emitted",
  "review.approved",
  "review.changes_requested",
  "review.requested",
  "run.completed",
  "run.failed",
  "run.queued",
  "run.started",
  "runner.allocated",
  "runner.failed",
  "runner.released",
  "task.completed",
  "task.failed",
  "task.queued",
  "task.started",
  "workspace.failed",
  "workspace.git_captured",
  "workspace.prepared",
  "writer.completed",
  "writer.failed",
  "writer.started",
  "writer.subtask.completed",
  "writer.subtask.failed",
  "writer.subtask.started"
] as const;

export type EventTypeName = (typeof eventTypeNames)[number];
