import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { tsType } from "./gen-dashboard-types.mjs";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const script = resolve(repoRoot, "scripts/gen-dashboard-types.mjs");
const generatedFile = resolve(repoRoot, "services/dashboard/src/api/http.gen.ts");

// Behavior of the JSON-Schema → TypeScript mapping. These assert the closed
// dialect the orchestrator's exporter actually emits maps to the right TS,
// independent of any specific contract — the durable invariant a future Rust
// (serde) arm of the same pipeline must also honor.
describe("jsonSchema → TS type mapping", () => {
  it("maps refined strings and primitives", () => {
    expect(tsType({ type: "string", minLength: 1 })).toBe("string");
    expect(tsType({ type: "integer", minimum: 0 })).toBe("number");
    expect(tsType({ type: "number" })).toBe("number");
    expect(tsType({ type: "boolean" })).toBe("boolean");
    expect(tsType({ type: "null" })).toBe("null");
  });

  it("maps string enums to a string-literal union", () => {
    expect(tsType({ enum: ["per_token", "subscription", "self_hosted"], type: "string" })).toBe(
      '"per_token" | "subscription" | "self_hosted"',
    );
  });

  it("maps a nullable field (anyOf with null) to `T | null`", () => {
    expect(tsType({ anyOf: [{ format: "date-time", type: "string" }, { type: "null" }] })).toBe("string | null");
  });

  it("maps the number|string id union", () => {
    expect(tsType({ anyOf: [{ type: "number" }, { type: "string" }] })).toBe("number | string");
  });

  it("maps an empty schema (z.unknown()) to `unknown`", () => {
    expect(tsType({})).toBe("unknown");
    expect(tsType({ default: [] })).toBe("unknown");
  });

  it("maps arrays, parenthesizing union element types", () => {
    expect(tsType({ type: "array", items: { type: "string" } })).toBe("string[]");
    expect(tsType({ type: "array", items: {} })).toBe("unknown[]");
    expect(tsType({ type: "array", items: { anyOf: [{ type: "number" }, { type: "string" }] } })).toBe(
      "Array<number | string>",
    );
  });

  it("maps an object to an inline literal with required vs optional keys", () => {
    const ts = tsType({
      type: "object",
      properties: { a: { type: "string" }, b: { type: "integer" } },
      required: ["a"],
    });
    expect(ts).toContain("a: string;");
    expect(ts).toContain("b?: number;");
  });

  it("throws on a construct outside the closed dialect (fail loud, never `any`)", () => {
    expect(() => tsType({ type: "tuple" })).toThrow(/unsupported schema type/);
  });
});

// The drift guarantee, asserted as a test too: the committed generated file is
// exactly what `--check` accepts. This is the same invariant the `just`
// dashboard-types-drift gate enforces in CI.
describe("dashboard generated types drift gate", () => {
  it("the committed http.gen.ts matches the JSON-Schema export (no drift)", () => {
    const result = spawnSync("node", [script, "--check"], { cwd: repoRoot, encoding: "utf8" });
    expect(result.stderr).toBe("");
    expect(result.status).toBe(0);
  });

  it("the committed file is marked @generated and re-derivable", () => {
    const text = readFileSync(generatedFile, "utf8");
    expect(text).toContain("@generated by scripts/gen-dashboard-types.mjs");
    expect(text).toContain("export interface RunDetail");
  });
});
