#!/usr/bin/env bash
# JIT env-image build pipeline (environment-management.md §4 + §7 P4).
#
# Builds a PROJECT ENVIRONMENT image — the golden BASE + the project's OFF-baseline
# toolchain baked in. Given the golden base image, the project's `mise.toml`, and the
# env_key, it generates a minimal BuildKit context (`FROM <golden-base>`; COPY the
# project's mise.toml into the shared mise dir; `mise trust && mise install` AS the
# `tanren` user so the off-baseline toolchain lands in the same shared mise dir the
# baseline warmed), tags it `env-<env_key>`, and pushes it to the registry.
#
# This is the env-layer counterpart of build-golden-image.sh (P2). It REUSES P2's
# BuildKit patterns verbatim: the dedicated docker-container builder, the
# insecure-local-registry buildkitd handling (the dev `registry:2` serves plain
# HTTP), and the `mode=max` registry cache (so the golden base layers + sibling-env
# installs are warm pulls). The JIT BUILD fires ONLY for an OFF-baseline toolchain —
# a baseline-subset project short-circuits to the golden base in the orchestrator and
# never invokes this script.
#
# Env knobs (all defaulted for local dev — CI overrides REGISTRY + PUSH):
#   GOLDEN_BASE_IMAGE  the golden base to FROM           (REQUIRED — never scratch)
#   MISE_TOML_PATH     path to the project's mise.toml   (REQUIRED)
#   ENV_KEY            the content key to tag/push by     (REQUIRED)
#   REGISTRY           registry host[:port][/ns]          (default localhost:5000)
#   IMAGE_NAME         image repo name under the registry (default tanren-env)
#   PUSH               1 → push image + cache to REGISTRY (default 0; build local)
#   PLATFORMS          buildx target platforms            (default host arch)
#
# Emits the pushed IMAGE REF on the LAST line so the orchestrator's build seam
# (engine/environments/creation/liveEnvBuildDriver.ts) captures it.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

GOLDEN_BASE_IMAGE="${GOLDEN_BASE_IMAGE:?GOLDEN_BASE_IMAGE is required - the golden base to FROM}"
MISE_TOML_PATH="${MISE_TOML_PATH:?MISE_TOML_PATH is required - the project mise.toml}"
ENV_KEY="${ENV_KEY:?ENV_KEY is required - the content key to tag and push by}"
REGISTRY="${REGISTRY:-localhost:5000}"
IMAGE_NAME="${IMAGE_NAME:-tanren-env}"
PUSH="${PUSH:-0}"

[ -f "$MISE_TOML_PATH" ] || { echo "[build-env-image] mise.toml not found: ${MISE_TOML_PATH}" >&2; exit 1; }

# The env_key IS the content tag (env-management.md §4: env images are tagged by
# env_key). Short-prefix to keep the tag readable + registry-safe (a tag is bounded);
# the full env_key still keys the registry ROW (the orchestrator stores the full key).
ENV_TAG="env-${ENV_KEY:0:32}"
IMAGE_REF="${REGISTRY}/${IMAGE_NAME}:${ENV_TAG}"
CACHE_REF="${REGISTRY}/${IMAGE_NAME}:buildcache"

echo "[build-env-image] repo            : ${REPO_ROOT}"
echo "[build-env-image] golden base     : ${GOLDEN_BASE_IMAGE}"
echo "[build-env-image] env_key         : ${ENV_KEY}"
echo "[build-env-image] image ref       : ${IMAGE_REF}"
echo "[build-env-image] push            : ${PUSH}"

# Generate the minimal BuildKit context in a temp dir: the env Dockerfile + the
# project's mise.toml. The Dockerfile FROMs the golden base (never scratch), drops the
# project's mise.toml into the shared mise dir as its GLOBAL config, and runs `mise
# trust && mise install` AS the `tanren` user (uid 1000) so the off-baseline toolchain
# is baked into the SAME shared mise dir the baseline warmed (the §3 Layer 3 delta).
BUILD_CTX="$(mktemp -d -t tanren-env-build.XXXXXX)"
trap 'rm -rf "$BUILD_CTX"' EXIT
cp "$MISE_TOML_PATH" "$BUILD_CTX/mise.toml"
# Write the Dockerfile from a QUOTED heredoc (everything literal — the `\` line
# continuations + the `${TANREN_MISE_*}` refs that must reach the BUILD shell, NOT this
# script's shell), with a `@GOLDEN_BASE@` placeholder substituted afterward so the only
# host-side interpolation is the one value we control (no quoting hazard).
cat > "$BUILD_CTX/Dockerfile" <<'DOCKERFILE'
# Generated by build-env-image.sh (env-management.md §4 / §7 P4). FROMs the golden
# base; bakes the project's OFF-baseline toolchain into the shared mise dir.
FROM @GOLDEN_BASE@
# The project's mise.toml — its declared toolchain (off-baseline versions/tools).
COPY mise.toml /opt/tanren/mise.toml
USER tanren
# Trust + install the project toolchain INTO the shared mise data dir (the same dir
# the golden baseline warmed), so a delta version/tool cold-installs once at BUILD
# time -> a warm hit at workspace-prep. MISE_GLOBAL_CONFIG_FILE points mise at the
# project's toml; the shared MISE_DATA_DIR/CACHE_DIR are inherited from the base env.
RUN set -eu; \
  export MISE_YES=1 MISE_GLOBAL_CONFIG_FILE=/opt/tanren/mise.toml \
    MISE_DATA_DIR="${TANREN_MISE_DATA_DIR}" MISE_CACHE_DIR="${TANREN_MISE_CACHE_DIR}"; \
  mise trust /opt/tanren/mise.toml; \
  mise install; \
  echo "=== env-image baked toolchain ==="; \
  mise ls --installed
USER root
DOCKERFILE
# Substitute the golden base ref into the placeholder (the one host-controlled value).
sed -i "s|@GOLDEN_BASE@|${GOLDEN_BASE_IMAGE}|g" "$BUILD_CTX/Dockerfile"

# REUSE P2's builder accommodations (build-golden-image.sh): a docker-container
# builder (required for registry cache export) with network=host (so a localhost:5000
# ref reaches the HOST-published dev registry, not the builder's own loopback) +
# insecure-registry config (the dev registry:2 serves plain HTTP, which BuildKit
# refuses by default). Only an http-style local host needs the insecure config; a real
# CI registry is HTTPS and needs neither.
BUILDER="tanren-env"
REGISTRY_HOST="${REGISTRY%%/*}"
BUILDKITD_CONFIG="$(mktemp -t tanren-env-buildkitd.XXXXXX.toml)"
trap 'rm -rf "$BUILD_CTX"; rm -f "$BUILDKITD_CONFIG"' EXIT
cat > "$BUILDKITD_CONFIG" <<EOF
[registry."${REGISTRY_HOST}"]
  http = true
  insecure = true
EOF

docker buildx rm "$BUILDER" >/dev/null 2>&1 || true
echo "[build-env-image] creating buildx builder '${BUILDER}' (docker-container driver, network=host)"
docker buildx create \
  --name "$BUILDER" \
  --driver docker-container \
  --driver-opt network=host \
  --buildkitd-config "$BUILDKITD_CONFIG" \
  --use >/dev/null

OUTPUT_ARGS=()
CACHE_TO_ARGS=()
if [ "$PUSH" = "1" ]; then
  OUTPUT_ARGS=(--push)
  CACHE_TO_ARGS=(--cache-to "type=registry,ref=${CACHE_REF},mode=max")
else
  OUTPUT_ARGS=(--load)
fi

PLATFORM_ARGS=()
if [ -n "${PLATFORMS:-}" ]; then
  PLATFORM_ARGS=(--platform "$PLATFORMS")
fi

set -x
docker buildx build \
  --builder "$BUILDER" \
  --file "$BUILD_CTX/Dockerfile" \
  --tag "$IMAGE_REF" \
  "${PLATFORM_ARGS[@]}" \
  --cache-from "type=registry,ref=${CACHE_REF}" \
  "${CACHE_TO_ARGS[@]}" \
  "${OUTPUT_ARGS[@]}" \
  "$BUILD_CTX"
set +x

echo "[build-env-image] built ${IMAGE_REF}"
if [ "$PUSH" = "1" ]; then
  echo "[build-env-image] pushed ${IMAGE_REF} (+ cache ${CACHE_REF}, mode=max) to ${REGISTRY}"
else
  echo "[build-env-image] loaded ${IMAGE_REF} into the local docker store (PUSH=0)"
fi
# Emit the image ref on the LAST line so the orchestrator's build seam captures it.
echo "${IMAGE_REF}"
