import type { SensitivityRule } from "./sensitivity.js";

function publicRules(eventName: string, paths: readonly string[]): SensitivityRule[] {
  return paths.map((path) => ({ eventName, path, tag: "public" }));
}

// Back-half cluster payloads contain only identifiers, classifications, counts,
// and digests. Raw symptoms, source bodies, hypotheses, and evidence content
// are intentionally absent from this event vocabulary.
export const resolutionClusterVocabularySensitivityRules: SensitivityRule[] = [
  ...publicRules("issue_loop.opened", ["projectId", "issueLoopId", "sourceFindingId"]),
  ...publicRules("issue_loop.source_revision_observed", [
    "projectId",
    "issueLoopId",
    "sourceFindingId",
    "sourceRevisionHash",
  ]),
  ...publicRules("issue_loop.reopened", ["projectId", "issueLoopId", "sourceFindingId"]),
  ...publicRules("issue_loop.verified", ["projectId", "issueLoopId", "resolutionJobId", "resolutionDecisionId"]),
  ...publicRules("spec.origin.linked", ["projectId", "issueLoopId", "specId", "sourceFindingId"]),
  ...publicRules("remediation.attempt.started", ["projectId", "issueLoopId", "remediationAttemptId", "iteration"]),
  ...publicRules("remediation.repair_routed", [
    "projectId",
    "issueLoopId",
    "remediationAttemptId",
    "specId",
    "failureSignatureHash",
  ]),
  ...publicRules("deployment.artifact.bound", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "releaseInstanceId",
    "artifactDigest",
  ]),
  ...publicRules("symptom.verification.started", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "contractId",
    "verificationRunId",
    "stage",
  ]),
  ...publicRules("symptom.verification.passed", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "verificationRunId",
    "classification",
    "assertionIds",
    "assertionIds[]",
    "evidenceRefs",
    "evidenceRefs[]",
  ]),
  ...publicRules("symptom.verification.failed", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "verificationRunId",
    "outcome",
    "classification",
    "assertionIds",
    "assertionIds[]",
    "evidenceRefs",
    "evidenceRefs[]",
  ]),
  ...publicRules("symptom.verification.inconclusive", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "verificationRunId",
    "outcome",
    "classification",
    "assertionIds",
    "assertionIds[]",
    "evidenceRefs",
    "evidenceRefs[]",
  ]),
  ...publicRules("symptom.soak.completed", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "verificationRunId",
    "assertionIds",
    "assertionIds[]",
    "evidenceRefs",
    "evidenceRefs[]",
  ]),
  ...publicRules("resolution.authorized", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "resolutionDecisionId",
    "inputSnapshotHash",
  ]),
  ...publicRules("resolution.blocked", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "resolutionDecisionId",
    "inputSnapshotHash",
  ]),
  ...publicRules("resolution.needs_attention", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "resolutionDecisionId",
    "inputSnapshotHash",
  ]),
  ...publicRules("resolution.waived", [
    "projectId",
    "issueLoopId",
    "resolutionJobId",
    "resolutionDecisionId",
    "inputSnapshotHash",
  ]),
  ...publicRules("source_issue.sync.enqueued", ["projectId", "issueLoopId", "sourceSyncOutboxId", "attempt"]),
  ...publicRules("source_issue.sync.succeeded", ["projectId", "issueLoopId", "sourceSyncOutboxId", "attempt"]),
  ...publicRules("source_issue.sync.failed", ["projectId", "issueLoopId", "sourceSyncOutboxId", "attempt"]),
  ...publicRules("source_issue.sync.drifted", [
    "projectId",
    "issueLoopId",
    "sourceSyncOutboxId",
    "observedRevisionHash",
  ]),
  ...publicRules("resolution.proof.sealed", ["projectId", "issueLoopId", "resolutionJobId", "proofHash"]),
];
